package app.qingting.music;
import org.junit.Test;import org.json.*;import java.util.*;import static org.junit.Assert.*;
public class LibraryStateTest {
 static Models.Song song(String title,String source)throws Exception{return new Models.Song(new Models.Route(source,source,new JSONObject().put("id",title).put("title",title).put("artist","Artist")));}
 @Test public void pinIsSnapshotAndRoundTrips()throws Exception{Models.Song s=song("A","one");s.routes.add(new Models.Route("two","two",s.routes.get(0).raw));Models.Song copy=s.snapshot(s.routes.get(1));s.routes.clear();assertEquals("two",copy.fixedRoute().sourceId);assertEquals("two",Models.Song.from(copy.json()).fixedRoute().sourceId);}
 @Test public void batchSkipsDuplicatesAndPreservesSource()throws Exception{LibraryState l=new LibraryState();String id=l.create("Road").id;Models.Song a=song("A","one");assertEquals(1,l.addToPlaylist(id,Arrays.asList(a.snapshot(a.routes.get(0)))));Models.Song other=song("A","two");assertEquals(0,l.addToPlaylist(id,Arrays.asList(other.snapshot(other.routes.get(0)))));assertEquals("one",l.playlist(id).songs.get(0).fixedRoute().sourceId);assertEquals(1,LibraryState.from(l.json()).playlist(id).songs.size());}
 @Test public void unknownSourceBatchIsAtomic()throws Exception{LibraryState l=new LibraryState();String id=l.create("X").id;Models.Song a=song("A","one"),b=song("B","two");b.sourceChoiceRequired=true;try{l.addToPlaylist(id,Arrays.asList(a.snapshot(a.routes.get(0)),b));fail();}catch(IllegalArgumentException expected){}assertTrue(l.playlist(id).songs.isEmpty());}
 @Test public void historyDeduplicatesAndCaps(){LibraryState l=new LibraryState();for(int i=0;i<35;i++)l.remember("q"+i);l.remember(" q34 ");assertEquals(30,l.history.size());assertEquals("q34",l.history.get(0));}
 @Test public void filtersAndStableSortDoNotChangeOriginal()throws Exception{List<Models.Song> s=Arrays.asList(song("B","one"),song("A","one"));assertEquals("A",LibraryState.filtered(s,"artist",3).get(0).title);assertEquals("B",s.get(0).title);assertTrue(LibraryState.filtered(s,"missing",0).isEmpty());}
 @Test public void malformedEntryDoesNotEraseFollowingSong()throws Exception{JSONObject j=new JSONObject().put("favorites",new JSONArray().put(new JSONObject()).put(song("A","one").json()));assertEquals(1,LibraryState.from(j).favorites.size());}
 @Test public void duplicateNamesRejected(){LibraryState l=new LibraryState();l.create("Road");try{l.create(" Road ");fail();}catch(IllegalArgumentException expected){}}
 @Test public void legacyMigrationSkipsCorruptItemAndPinsSingleRoute()throws Exception{JSONArray a=new JSONArray().put(song("A","one").json()).put(new JSONObject()).put(song("B","two").json());LibraryState l=LibraryState.migrateLegacy(a);assertEquals(2,l.favorites.size());assertEquals("two",l.favorites.get(1).fixedRoute().sourceId);}
 @Test public void snapshotCanPinSuccessfulRouteFromAnotherSearch()throws Exception{Models.Song s=song("A","one"),other=song("A","two");Models.Song copy=s.snapshot(other.routes.get(0));assertNotNull(copy.fixedRoute());assertEquals("two",copy.fixedRoute().sourceId);}
}
