package app.qingting.music;
import android.graphics.*;import androidx.test.ext.junit.runners.AndroidJUnit4;import androidx.test.platform.app.InstrumentationRegistry;import java.io.*;import java.net.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;import org.junit.Test;import org.junit.runner.RunWith;import static org.junit.Assert.*;
@RunWith(AndroidJUnit4.class)
public class ArtworkLoadingTest {
 @Test public void sameUrlSharesDownloadAndCancellingOneSubscriberKeepsOther()throws Exception{
  android.app.Instrumentation i=InstrumentationRegistry.getInstrumentation();ByteArrayOutputStream png=new ByteArrayOutputStream();Bitmap.createBitmap(2,2,Bitmap.Config.ARGB_8888).compress(Bitmap.CompressFormat.PNG,100,png);byte[] body=png.toByteArray();CountDownLatch request=new CountDownLatch(1),release=new CountDownLatch(1),loaded=new CountDownLatch(1);AtomicInteger cancelledCallbacks=new AtomicInteger(),otherCallbacks=new AtomicInteger();
  try(ServerSocket server=new ServerSocket(0)){server.setSoTimeout(5000);Thread worker=new Thread(()->{try(Socket socket=server.accept()){socket.setSoTimeout(5000);BufferedReader input=new BufferedReader(new InputStreamReader(socket.getInputStream()));String line;while((line=input.readLine())!=null&&!line.isEmpty()){}request.countDown();release.await(5,TimeUnit.SECONDS);OutputStream out=socket.getOutputStream();out.write(("HTTP/1.1 200 OK\r\nContent-Type: image/png\r\nContent-Length: "+body.length+"\r\nConnection: close\r\n\r\n").getBytes(java.nio.charset.StandardCharsets.US_ASCII));out.write(body);out.flush();}catch(Exception ignored){}});worker.start();String url="http://127.0.0.1:"+server.getLocalPort()+"/cover-"+System.nanoTime();Runnable[] cancel=new Runnable[2];i.runOnMainSync(()->{ArtworkLoader loader=ArtworkLoader.get(i.getTargetContext());cancel[0]=loader.load(url,b->cancelledCallbacks.incrementAndGet());cancel[1]=loader.load(url,b->{if(b!=null){otherCallbacks.incrementAndGet();loaded.countDown();}});});assertTrue(request.await(5,TimeUnit.SECONDS));i.runOnMainSync(cancel[0]);release.countDown();assertTrue(loaded.await(5,TimeUnit.SECONDS));assertEquals(0,cancelledCallbacks.get());assertEquals(1,otherCallbacks.get());i.runOnMainSync(()->{assertNotNull(ArtworkLoader.get(i.getTargetContext()).cached(url));cancel[1].run();});worker.join(1000);}
 }
}
