package app.qingting.music;
import android.app.*;import android.content.*;import android.os.Bundle;import android.view.*;import android.widget.*;import androidx.test.ext.junit.runners.AndroidJUnit4;import androidx.test.platform.app.InstrumentationRegistry;import org.json.*;import org.junit.Test;import org.junit.runner.RunWith;import java.util.*;import java.util.concurrent.atomic.*;import static org.junit.Assert.*;
@RunWith(AndroidJUnit4.class) @androidx.media3.common.util.UnstableApi
public class SheetIntegrationTest {
 private final Instrumentation i=InstrumentationRegistry.getInstrumentation();
 private void ui(Runnable run){i.runOnMainSync(run);}
 private void until(java.util.function.BooleanSupplier condition)throws Exception{AtomicBoolean done=new AtomicBoolean();long end=System.currentTimeMillis()+30000;while(System.currentTimeMillis()<end){ui(()->done.set(condition.getAsBoolean()));if(done.get())return;Thread.sleep(100);}throw new AssertionError("sheet operation timed out");}
 @Test public void realPluginRuntimeSupportsSheetsPagingCacheAndPinnedFavorite()throws Exception{
  Context context=i.getTargetContext();SharedPreferences.Editor defaults=context.getSharedPreferences("library",0).edit();for(String url:MusicRepository.DEFAULT_SUBSCRIPTIONS)defaults.putBoolean("defaultAttempted:"+url,true);defaults.commit();Activity a=i.startActivitySync(new Intent(context,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));MusicRepository repo=((MusicApp)a.getApplication()).repository;List<Models.Source> original=new ArrayList<>(repo.sources);
  Models.Source source=new Models.Source("fixture:sheet:"+UUID.randomUUID());source.name="歌单测试";source.script="module.exports={platform:'歌单测试',supportedSearchType:['sheet'],search(q,p,t){if(t!=='sheet')throw Error('wrong type');return {data:[{id:'s',title:q,token:'keep'}],isEnd:true}},getMusicSheetInfo(s,p){if(s.token!=='keep'||p>1&&s.cursor!=='next')throw Error('lost fields');return {musicList:p===1?[]:[{id:p,title:'测试歌曲'+p,artist:'本地',url:'https://example.invalid/song'}],isEnd:p>=3,sheetItem:{cursor:'next'}}}}";
  try{ui(()->{repo.sources.clear();repo.sources.add(source);repo.sheets.search("通勤",true);});until(()->!repo.sheets.searching);ui(()->{assertEquals(1,repo.sheets.items.size());repo.sheets.open(repo.sheets.items.get(0),true);});until(()->!repo.sheets.loadingDetail);ui(()->{assertEquals(0,repo.sheets.detail.songs.size());assertFalse(repo.sheets.detail.end);repo.sheets.loadDetail();});until(()->!repo.sheets.loadingDetail);ui(()->repo.sheets.loadDetail());until(()->!repo.sheets.loadingDetail);
   Sheets.Detail[] cached={null};ui(()->{cached[0]=repo.sheets.detail;assertEquals(2,cached[0].songs.size());assertTrue(cached[0].end);repo.sheets.closeDetail();repo.sheets.open(cached[0].item,false);assertSame(cached[0],repo.sheets.detail);Models.Song song=cached[0].songs.get(0);Models.Song pinned=song.snapshot(song.routes.get(0));assertEquals(source.id,pinned.fixedRoute().sourceId);assertEquals(0,source.failures);});
  }finally{ui(()->{repo.sheets.search("",false);repo.sources.clear();repo.sources.addAll(original);a.finish();});}
 }
 @Test public void sheetRowsRecycleAndLocalNameFilterKeepsInput()throws Exception{
  Context context=i.getTargetContext();Activity a=i.startActivitySync(new Intent(context,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));MusicRepository repo=((MusicApp)a.getApplication()).repository;LibraryState original=repo.library;SongListView[] list={null};LibraryUi[] library={null};AtomicInteger created=new AtomicInteger(),reused=new AtomicInteger();
  try{ui(()->{list[0]=new SongListView(a);List<String> values=new ArrayList<>();for(int n=0;n<500;n++)values.add("sheet"+n);list[0].items(values,2,(value,old,parent)->{TextView row;if(old==null){created.incrementAndGet();row=new TextView(a);row.setMinHeight(72);}else{reused.incrementAndGet();row=(TextView)old;}row.setText((String)value);return row;});a.setContentView(list[0]);});i.waitForIdleSync();ui(()->list[0].setSelection(400));i.waitForIdleSync();ui(()->{assertTrue(created.get()<100);assertTrue(reused.get()>0);assertTrue(list[0].songRows().isEmpty());repo.library=new LibraryState();repo.library.create("通勤");repo.library.create("睡前");list[0]=new SongListView(a);library[0]=new LibraryUi(a,repo,()->{});library[0].attachList(list[0]);library[0].render(list[0].header);a.setContentView(list[0]);});i.waitForIdleSync();ui(()->{EditText input=findInput(list[0].header);assertNotNull(input);input.requestFocus();input.setText("通勤");assertEquals(1,list[0].songCount());assertSame(input,findInput(list[0].header));assertTrue(input.hasFocus());});
  }finally{ui(()->{repo.library=original;a.finish();});}
 }
 @Test public void asyncDetailUpdateKeepsFilterFocusAndComposingText()throws Exception{
  Context context=i.getTargetContext();Activity a=i.startActivitySync(new Intent(context,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));MusicRepository repo=((MusicApp)a.getApplication()).repository;Sheets.Detail original=repo.sheets.detail;Models.Source source=new Models.Source("fixture:focus");Sheets.Item item=new Sheets.Item(source,new JSONObject().put("id",1).put("title","test"),null);Sheets.Detail initial=new Sheets.Detail(item),loaded=initial.append(new JSONObject().put("musicList",new JSONArray().put(new JSONObject().put("id",1).put("title","abc"))));
  try{ui(()->{repo.sheets.detail=initial;SongListView list=new SongListView(a);SheetUi screen=new SheetUi(a,repo,()->{},(song,old,parent)->{TextView row=old instanceof TextView?(TextView)old:new TextView(a);row.setText(song.title);return row;});screen.render(list);a.setContentView(list);EditText input=findInput(list.header);input.requestFocus();input.setText("a");input.setSelection(1);android.view.inputmethod.BaseInputConnection.setComposingSpans(input.getText());repo.sheets.detail=loaded;assertTrue(screen.updateDetail(list));assertSame(input,findInput(list.header));assertTrue(input.hasFocus());assertEquals(1,input.getSelectionStart());assertTrue(android.view.inputmethod.BaseInputConnection.getComposingSpanStart(input.getText())>=0);assertEquals(1,list.songCount());});}finally{ui(()->{repo.sheets.detail=original;a.finish();});}
 }
 private EditText findInput(View v){if(v instanceof EditText)return (EditText)v;if(v instanceof ViewGroup)for(int n=0;n<((ViewGroup)v).getChildCount();n++){EditText found=findInput(((ViewGroup)v).getChildAt(n));if(found!=null)return found;}return null;}
}
