package app.qingting.music;
import android.app.*;import android.content.*;import android.os.Bundle;import android.view.*;import android.widget.*;import androidx.test.ext.junit.runners.AndroidJUnit4;import androidx.test.platform.app.InstrumentationRegistry;import java.util.*;import java.util.concurrent.atomic.AtomicInteger;import org.json.JSONObject;import org.junit.Test;import org.junit.runner.RunWith;import static org.junit.Assert.*;
@RunWith(AndroidJUnit4.class) @androidx.media3.common.util.UnstableApi
public class SmoothnessUiTest {
 @Test public void fiveHundredSongsUseBoundedViewsAndReuseRows()throws Exception{
  Instrumentation i=InstrumentationRegistry.getInstrumentation();Context c=i.getTargetContext();Activity activity=i.startActivitySync(new Intent(c,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));List<Models.Song> songs=new ArrayList<>();Models.Source source=new Models.Source("test");for(int n=0;n<500;n++)songs.add(new Models.Song(new Models.Route(source,new JSONObject().put("id",n).put("title","song"+n))));SongListView[] list={null};AtomicInteger created=new AtomicInteger(),reused=new AtomicInteger();
  try{i.runOnMainSync(()->{list[0]=new SongListView(activity);list[0].songs(songs,0,(song,old,parent)->{TextView row;if(old==null){created.incrementAndGet();row=new TextView(activity);row.setMinHeight(Math.round(72*activity.getResources().getDisplayMetrics().density));}else{reused.incrementAndGet();row=(TextView)old;}row.setText(song.title);return row;});activity.setContentView(list[0]);});i.waitForIdleSync();i.runOnMainSync(()->{assertEquals(500,list[0].songCount());assertTrue(created.get()<40);assertTrue(list[0].songRows().size()<30);list[0].setSelection(400);});i.waitForIdleSync();i.runOnMainSync(()->{assertTrue(created.get()<60);assertTrue(reused.get()>0);for(View row:list[0].songRows())assertEquals(((Models.Song)row.getTag()).title,((TextView)row).getText().toString());String anchor=songs.get(400).key;assertEquals(401,list[0].positionOf(anchor));List<Models.Song> reduced=new ArrayList<>(songs);reduced.remove(0);list[0].songs(reduced,0,(song,old,parent)->{TextView row=old instanceof TextView?(TextView)old:new TextView(activity);row.setText(song.title);return row;});assertEquals(400,list[0].positionOf(anchor));});}finally{i.runOnMainSync(activity::finish);}
 }
 @Test public void batchSelectionIncludesOffscreenSongsAndSurvivesRecycling()throws Exception{
  Instrumentation i=InstrumentationRegistry.getInstrumentation();Context c=i.getTargetContext();Activity activity=i.startActivitySync(new Intent(c,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));MusicRepository repo=((MusicApp)activity.getApplication()).repository;List<Models.Song> original=new ArrayList<>(repo.favorites),songs=new ArrayList<>();Models.Source source=new Models.Source("test");for(int n=0;n<500;n++)songs.add(new Models.Song(new Models.Route(source,new JSONObject().put("id",n).put("title","song"+n))));SongListView[] list={null};LibraryUi[] library={null};
  try{i.runOnMainSync(()->{repo.favorites.clear();repo.favorites.addAll(songs);list[0]=new SongListView(activity);library[0]=new LibraryUi(activity,repo,()->{});library[0].attachList(list[0]);Bundle state=new Bundle();state.putString("libraryPage","favorites");state.putBoolean("librarySelecting",true);library[0].restore(state);library[0].render(list[0].header);activity.setContentView(list[0]);});i.waitForIdleSync();java.lang.reflect.Field all=LibraryUi.class.getDeclaredField("selectionAll");all.setAccessible(true);TextView select=(TextView)all.get(library[0]);i.runOnMainSync(()->{select.performClick();assertEquals("取消全选",select.getText().toString());list[0].setSelection(400);});i.waitForIdleSync();i.runOnMainSync(()->{assertTrue(list[0].songRows().size()<30);for(View row:list[0].songRows())assertTrue(((CheckBox)((ViewGroup)row).getChildAt(0)).isChecked());select.performClick();for(View row:list[0].songRows())assertFalse(((CheckBox)((ViewGroup)row).getChildAt(0)).isChecked());});}finally{i.runOnMainSync(()->{repo.favorites.clear();repo.favorites.addAll(original);activity.finish();});}
 }
}
