package app.qingting.music;
import android.content.Context;import android.graphics.*;import android.view.View;import android.util.LruCache;import java.util.concurrent.*;
/** Bounded, shared image cache; visual animation never owns playback. */
public final class ArtworkView extends View {
 private Runnable cancel;private boolean temporarilyDetached;
 private final Paint paint=new Paint(3);private final boolean record;private Bitmap image;private String url="";private float angle;private boolean running;private long last;
 public ArtworkView(Context c,boolean record){super(c);this.record=record;setContentDescription(record?"唱片封面，点击切换歌词":"歌曲封面");}
 public void bind(Models.Song song){String next="";if(song!=null&&!song.routes.isEmpty()){org.json.JSONObject raw=(song.fixedRoute()!=null?song.fixedRoute():song.routes.get(0)).raw;for(String key:new String[]{"artwork","cover","picUrl","albumPic","image"}){String v=raw.optString(key);if(v.startsWith("https://")||v.startsWith("http://")){next=v;break;}}}if(next.equals(url)){if(image==null&&isAttachedToWindow())request();return;}stopRequest();url=next;image=ArtworkLoader.get(getContext()).cached(next);invalidate();if(isAttachedToWindow())request();}
 private void request(){if(temporarilyDetached||url.isEmpty()||image!=null||cancel!=null)return;String expected=url;cancel=ArtworkLoader.get(getContext()).load(url,result->{if(url.equals(expected)){image=result;invalidate();}});}
 private void stopRequest(){if(cancel!=null){cancel.run();cancel=null;}}
 @Override protected void onAttachedToWindow(){super.onAttachedToWindow();request();}
 @Override public void onStartTemporaryDetach(){temporarilyDetached=true;stopRequest();super.onStartTemporaryDetach();}
 @Override public void onFinishTemporaryDetach(){super.onFinishTemporaryDetach();temporarilyDetached=false;if(isAttachedToWindow())request();}
 public void running(boolean value){if(running==value)return;running=value;last=android.os.SystemClock.elapsedRealtime();invalidate();}
 @Override protected void onDetachedFromWindow(){stopRequest();running=false;super.onDetachedFromWindow();}
 @Override protected void onDraw(Canvas c){super.onDraw(c);if(!record){drawSquare(c);return;}float w=getWidth(),h=getHeight(),r=Math.min(w,h)*.44f,cx=w/2,cy=h/2;if(running){long now=android.os.SystemClock.elapsedRealtime();angle+=(now-last)*.009f;last=now;postInvalidateDelayed(32);}c.save();c.rotate(record?angle:0,cx,cy);paint.setColor(record?0xff25332f:0xffdce7de);c.drawCircle(cx,cy,r,paint);if(record){paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(1);paint.setColor(0xff3c4c43);for(float ring=.55f;ring<1;ring+=.08f)c.drawCircle(cx,cy,r*ring,paint);paint.setStyle(Paint.Style.FILL);}float photo=record?r*.68f:r;Path clip=new Path();clip.addCircle(cx,cy,photo,Path.Direction.CW);c.save();c.clipPath(clip);if(image!=null){int edge=Math.min(image.getWidth(),image.getHeight());Rect src=new Rect((image.getWidth()-edge)/2,(image.getHeight()-edge)/2,(image.getWidth()+edge)/2,(image.getHeight()+edge)/2);c.drawBitmap(image,src,new RectF(cx-photo,cy-photo,cx+photo,cy+photo),paint);}else{paint.setColor(0xff72977e);c.drawCircle(cx,cy,photo,paint);paint.setColor(0xffeff5ea);paint.setTextAlign(Paint.Align.CENTER);paint.setTextSize(photo);c.drawText("♪",cx,cy+photo*.32f,paint);}c.restore();if(record){paint.setColor(0xffd6decf);c.drawCircle(cx,cy,r*.045f,paint);}c.restore();}
 private void drawSquare(Canvas canvas){float inset=getWidth()*.04f;RectF rect=new RectF(inset,inset,getWidth()-inset,getHeight()-inset);Path path=new Path();path.addRoundRect(rect,getWidth()*.18f,getWidth()*.18f,Path.Direction.CW);canvas.save();canvas.clipPath(path);paint.setColor(0xffdce7de);canvas.drawRect(rect,paint);if(image!=null){int edge=Math.min(image.getWidth(),image.getHeight());Rect src=new Rect((image.getWidth()-edge)/2,(image.getHeight()-edge)/2,(image.getWidth()+edge)/2,(image.getHeight()+edge)/2);canvas.drawBitmap(image,src,rect,paint);}else{paint.setColor(0xff72977e);paint.setTextAlign(Paint.Align.CENTER);paint.setTextSize(getWidth()*.5f);canvas.drawText("♪",getWidth()/2f,getHeight()*.67f,paint);}canvas.restore();}
}
