package app.qingting.music;
import android.app.*;import android.os.Bundle;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.*;import android.content.res.ColorStateList;import android.view.*;import android.widget.*;import android.text.*;import java.util.*;import static app.qingting.music.Models.*;
/** Local library screen and the sole add-to-playlist surface. */
@androidx.media3.common.util.UnstableApi
public final class LibraryUi {
 private final int ink=0xff25332c,muted=0xff7c877f,green=0xff245e4f;
 private final Activity a;private final MusicRepository repo;private final Runnable redraw;private String page="home",filter="";private boolean selecting;private final Set<String> selected=new HashSet<>();
 public LibraryUi(Activity a,MusicRepository repo,Runnable redraw){this.a=a;this.repo=repo;this.redraw=redraw;}
 public void restore(Bundle b){if(b==null)return;page=b.getString("libraryPage","home");filter=b.getString("libraryFilter","");selecting=b.getBoolean("librarySelecting");ArrayList<String> keys=b.getStringArrayList("librarySelection");if(keys!=null)selected.addAll(keys);}
 private LinearLayout dock;private SongListView songList;private List<Song> displayed=Collections.emptyList();private TextView selectionCount,selectionAdd,selectionAll;private boolean updatingChecks;
 public void attachList(SongListView list){songList=list;}
 public void attachDock(LinearLayout dock){this.dock=dock;}
 public boolean handleBack(){if(selecting){selecting=false;selected.clear();redraw.run();return true;}if(!page.equals("home")&&!page.equals("playlists")){open("home");return true;}return false;}
 public void leaveSelection(){selecting=false;selected.clear();}
 private void updateSelection(){if(updatingChecks)return;updatingChecks=true;if(songList!=null)for(View view:songList.songRows())if(view instanceof LibrarySongRow)((LibrarySongRow)view).selection();if(selectionAll!=null)selectionAll.setText(!displayed.isEmpty()&&displayed.stream().allMatch(v->selected.contains(v.key))?"取消全选":"全选");if(selectionCount!=null)selectionCount.setText("已选 "+selected.size()+" 首");if(selectionAdd!=null){selectionAdd.setEnabled(!selected.isEmpty());selectionAdd.setAlpha(selected.isEmpty()?.4f:1f);}updatingChecks=false;}
 public String pageKey(){return page;}
 public void save(Bundle b){b.putString("libraryPage",page);b.putString("libraryFilter",filter);b.putBoolean("librarySelecting",selecting);b.putStringArrayList("librarySelection",new ArrayList<>(selected));}
 private int dp(int n){return (int)(n*a.getResources().getDisplayMetrics().density+.5f);}
 private LinearLayout row(){LinearLayout l=new LinearLayout(a);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
 private LinearLayout column(){LinearLayout l=new LinearLayout(a);l.setOrientation(LinearLayout.VERTICAL);return l;}
 private TextView text(String value,int size,int color,boolean bold){TextView t=new TextView(a);t.setText(value);t.setTextSize(size);t.setTextColor(color);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
 private GradientDrawable shape(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
 private Drawable ripple(int color,int radius){return new RippleDrawable(ColorStateList.valueOf(0x18245e4f),shape(color,radius),shape(Color.WHITE,radius));}
 private void space(LinearLayout host,int h){host.addView(new View(a),new LinearLayout.LayoutParams(1,dp(h)));}
 private void gap(LinearLayout host,int w){host.addView(new View(a),new LinearLayout.LayoutParams(dp(w),1));}
 private void weight(LinearLayout host,View view){host.addView(view,new LinearLayout.LayoutParams(0,-2,1));}
 private TextView button(String label,Runnable action){TextView t=text(label,14,green,false);t.setGravity(Gravity.CENTER);t.setMinHeight(dp(48));t.setMinWidth(dp(48));t.setPadding(dp(10),0,dp(10),0);t.setBackground(ripple(Color.TRANSPARENT,12));t.setOnClickListener(v->action.run());return t;}
 private ImageButton icon(int drawable,String description,Runnable action){ImageButton b=new ImageButton(a);b.setImageResource(drawable);b.setImageTintList(ColorStateList.valueOf(green));b.setContentDescription(description);b.setTooltipText(description);b.setPadding(dp(12),dp(12),dp(12),dp(12));b.setBackground(ripple(Color.TRANSPARENT,12));b.setLayoutParams(new LinearLayout.LayoutParams(dp(48),dp(48)));b.setOnClickListener(v->action.run());return b;}
 private View badge(int drawable,int size,int background,int tint){FrameLayout frame=new FrameLayout(a);frame.setBackground(shape(background,16));ImageView image=new ImageView(a);image.setImageResource(drawable);image.setImageTintList(ColorStateList.valueOf(tint));frame.addView(image,new FrameLayout.LayoutParams(dp(size/2),dp(size/2),Gravity.CENTER));frame.setLayoutParams(new LinearLayout.LayoutParams(dp(size),dp(size)));frame.setImportantForAccessibility(View.IMPORTANT_FOR_ACCESSIBILITY_NO);return frame;}
 private void oneLine(TextView view){view.setSingleLine(true);view.setEllipsize(TextUtils.TruncateAt.END);}
 private List<Song> source(){if(page.equals("favorites"))return repo.favorites;if(page.equals("recent"))return repo.recent;LibraryState.Playlist p=repo.library.playlist(page);return p==null?Collections.emptyList():p.songs;}
 public void render(LinearLayout host){if(dock!=null){dock.removeAllViews();dock.setVisibility(View.GONE);}
  if(page.equals("home")||page.equals("playlists")){home(host);return;}
  boolean favorites=page.equals("favorites"),recent=page.equals("recent");LibraryState.Playlist playlist=repo.library.playlist(page);
  if(!favorites&&!recent&&playlist==null){page="home";home(host);return;}
  selected.retainAll(new HashSet<>(source().stream().map(v->v.key).collect(java.util.stream.Collectors.toList())));
  LinearLayout navigation=row();TextView back=button("返回我的音乐",()->open("home"));back.setGravity(Gravity.CENTER_VERTICAL);back.setBackground(ripple(Color.TRANSPARENT,12));back.setPadding(0,0,dp(12),0);Drawable arrow=a.getDrawable(R.drawable.library_back);arrow.setBounds(0,0,dp(20),dp(20));back.setCompoundDrawablesRelative(arrow,null,null,null);back.setCompoundDrawablePadding(dp(8));back.setContentDescription("返回我的音乐首页");navigation.addView(back,new LinearLayout.LayoutParams(-2,dp(48)));navigation.addView(new View(a),new LinearLayout.LayoutParams(0,1,1));if(playlist!=null)navigation.addView(icon(R.drawable.player_more,"管理歌单",()->playlistMenu(playlist)));host.addView(navigation,new LinearLayout.LayoutParams(-1,dp(48)));space(host,12);
  LinearLayout heading=row();heading.addView(badge(favorites?R.drawable.player_heart_filled:recent?R.drawable.library_recent:R.drawable.library_playlist,44,favorites?0xffdce9df:0xffe9ede4,green));gap(heading,12);LinearLayout names=column();TextView title=text(favorites?"我的收藏":recent?"最近播放":playlist.name,22,ink,true);title.setMaxLines(2);title.setEllipsize(TextUtils.TruncateAt.END);names.addView(title);space(names,5);names.addView(text(source().size()+" 首歌曲"+(favorites?" · 已保存收藏来源":""),12,muted,false));weight(heading,names);host.addView(heading);space(host,14);
  LinearLayout tools=row();LinearLayout field=row();field.setBackground(shape(0xffecefe9,14));field.setPadding(dp(12),0,dp(8),0);ImageView search=new ImageView(a);search.setImageResource(R.drawable.library_search);search.setImageTintList(ColorStateList.valueOf(muted));field.addView(search,new LinearLayout.LayoutParams(dp(18),dp(18)));gap(field,8);EditText input=new EditText(a);input.setSingleLine(true);input.setTextSize(14);input.setTextColor(ink);input.setHintTextColor(muted);input.setHint("搜索歌名、歌手");input.setBackgroundColor(Color.TRANSPARENT);input.setPadding(0,0,0,0);input.setText(filter);field.addView(input,new LinearLayout.LayoutParams(0,dp(48),1));weight(tools,field);gap(tools,4);tools.addView(icon(R.drawable.library_sort,"排序："+LibraryState.SORTS[repo.sortPreference(page)],()->new UiSheet.Builder(a).setTitle("列表排序").setSingleChoiceItems(LibraryState.SORTS,repo.sortPreference(page),(d,w)->{repo.sortPreference(page,w);d.dismiss();redraw.run();}).show()));host.addView(tools);space(host,10);
  LinearLayout list=column();host.addView(list);Runnable update=()->renderSongs(list,favorites,recent);update.run();input.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int count,int after){}public void onTextChanged(CharSequence s,int st,int before,int count){filter=s.toString();selected.clear();update.run();}public void afterTextChanged(Editable e){}});
 }
 private void home(LinearLayout host){
  space(host,8);host.addView(text("我的音乐",28,ink,true));space(host,6);host.addView(text("收藏、歌单与听过的歌",13,muted,false));space(host,24);
  LinearLayout shortcuts=row();shortcuts.addView(shortcut("我的收藏",repo.favorites.size()+" 首喜欢的歌",R.drawable.player_heart_filled,0xffdfece3,"favorites"),new LinearLayout.LayoutParams(0,-2,1));gap(shortcuts,12);shortcuts.addView(shortcut("最近播放",repo.recent.size()+" 首听过的歌",R.drawable.library_recent,0xffeaece3,"recent"),new LinearLayout.LayoutParams(0,-2,1));host.addView(shortcuts);space(host,24);
  LinearLayout heading=row();weight(heading,text("自建歌单",19,ink,true));heading.addView(text(String.valueOf(repo.library.playlists.size()),13,muted,false));gap(heading,8);heading.addView(icon(R.drawable.library_add,"新建歌单",()->name(null,null)));host.addView(heading);space(host,4);
  if(repo.library.playlists.isEmpty()){empty(host,R.drawable.library_playlist,"创建你的第一张歌单","建好歌单后，从我的收藏批量添加歌曲。","新建歌单",()->name(null,null));return;}
  for(LibraryState.Playlist playlist:repo.library.playlists){LinearLayout item=row();item.setMinimumHeight(dp(80));LinearLayout entry=row();entry.setPadding(0,dp(8),0,dp(8));entry.setBackground(ripple(Color.TRANSPARENT,12));if(playlist.songs.isEmpty())entry.addView(badge(R.drawable.library_playlist,56,0xffe5ebe2,green));else{ArtworkView cover=new ArtworkView(a,false);cover.bind(playlist.songs.get(0));entry.addView(cover,new LinearLayout.LayoutParams(dp(56),dp(56)));}gap(entry,14);LinearLayout copy=column();TextView name=text(playlist.name,16,ink,true);oneLine(name);copy.addView(name);space(copy,5);copy.addView(text(playlist.songs.size()+" 首歌曲",12,muted,false));weight(entry,copy);entry.setContentDescription("打开歌单 "+playlist.name+"，"+playlist.songs.size()+" 首歌曲");entry.setOnClickListener(v->open(playlist.id));weight(item,entry);item.addView(icon(R.drawable.player_more,"管理歌单 "+playlist.name,()->playlistMenu(playlist)));host.addView(item);}
 }
 private LinearLayout shortcut(String title,String subtitle,int drawable,int background,String target){LinearLayout tile=column();tile.setBackground(ripple(background,20));tile.setPadding(dp(16),dp(16),dp(12),dp(16));ImageView icon=new ImageView(a);icon.setImageResource(drawable);icon.setImageTintList(ColorStateList.valueOf(green));tile.addView(icon,new LinearLayout.LayoutParams(dp(28),dp(28)));space(tile,14);tile.addView(text(title,17,ink,true));space(tile,5);tile.addView(text(subtitle,12,muted,false));tile.setContentDescription(title+"，"+subtitle);tile.setOnClickListener(v->open(target));return tile;}
 private void renderSongs(LinearLayout list,boolean favorites,boolean recent){
  list.removeAllViews();selectionCount=null;selectionAdd=null;selectionAll=null;if(dock!=null){dock.removeAllViews();dock.setVisibility(View.GONE);}List<Song> visible=LibraryState.filtered(source(),filter,repo.sortPreference(page));displayed=visible;if(songList!=null)songList.songs(visible,1,(song,recycled,parent)->libraryRow(song,visible,favorites,recent,recycled));LinearLayout bar=row();
  if(selecting&&favorites){
   weight(bar,text("选择歌曲",15,ink,true));selectionAll=button(!visible.isEmpty()&&visible.stream().allMatch(v->selected.contains(v.key))?"取消全选":"全选",()->{boolean all=!visible.isEmpty()&&visible.stream().allMatch(v->selected.contains(v.key));for(Song song:visible)if(all)selected.remove(song.key);else selected.add(song.key);updateSelection();});selectionAll.setEnabled(!visible.isEmpty());bar.addView(selectionAll);bar.addView(button("取消",()->{selecting=false;selected.clear();redraw.run();}));list.addView(bar);
   LinearLayout batch=row();batch.setPadding(dp(8),dp(6),dp(8),dp(6));selectionCount=text("已选 "+selected.size()+" 首",14,ink,true);weight(batch,selectionCount);selectionAdd=button("添加到歌单",()->{List<Song> picked=new ArrayList<>();for(Song song:visible)if(selected.contains(song.key))picked.add(song);addToPlaylist(picked);});selectionAdd.setTextColor(Color.WHITE);selectionAdd.setBackground(ripple(green,14));selectionAdd.setEnabled(!selected.isEmpty());selectionAdd.setAlpha(selected.isEmpty()?.4f:1f);batch.addView(selectionAdd);if(dock!=null){dock.setVisibility(View.VISIBLE);dock.addView(batch);}else list.addView(batch);space(list,8);
  }else{
   LinearLayout play=row();play.setMinimumHeight(dp(48));ImageView mark=new ImageView(a);mark.setImageResource(R.drawable.player_play);mark.setImageTintList(ColorStateList.valueOf(Color.WHITE));mark.setBackground(shape(green,18));mark.setPadding(dp(8),dp(8),dp(8),dp(8));play.addView(mark,new LinearLayout.LayoutParams(dp(32),dp(32)));gap(play,10);play.addView(text("播放全部",15,ink,true));gap(play,8);play.addView(text(String.valueOf(visible.size()),12,muted,false));play.setBackground(ripple(Color.TRANSPARENT,12));play.setEnabled(!visible.isEmpty());play.setAlpha(visible.isEmpty()?.4f:1f);play.setContentDescription("播放当前列表全部 "+visible.size()+" 首歌曲");play.setOnClickListener(v->{if(!visible.isEmpty())PlaybackUi.play(a,repo,visible.get(0),visible);});weight(bar,play);if(favorites){TextView batch=button("批量",()->{selecting=true;redraw.run();});batch.setEnabled(!visible.isEmpty());batch.setAlpha(visible.isEmpty()?.4f:1f);bar.addView(batch);}list.addView(bar);space(list,4);
  }
  if(visible.isEmpty()){boolean filtered=!source().isEmpty();empty(list,filtered?R.drawable.library_search:recent?R.drawable.library_recent:R.drawable.library_playlist,filtered?"没有找到匹配歌曲":favorites?"把喜欢的歌留在这里":recent?"还没有播放记录":"歌单还是空的",filtered?"试试其他歌名或歌手。":favorites?"播放时点爱心，即可收藏歌曲和来源。":recent?"播放过的歌曲会自动出现在这里。":"请从我的收藏选择歌曲，添加到这张歌单。",null,null);return;}
 }
 private final class LibrarySongRow extends LinearLayout {
  final CheckBox check;final ArtworkView cover;final TextView title,artist,origin;final ImageButton more;final LinearLayout entry;Song song;List<Song> queue;boolean favorites,recent;
  LibrarySongRow(){super(a);setOrientation(HORIZONTAL);setGravity(Gravity.CENTER_VERTICAL);setMinimumHeight(dp(72));check=new CheckBox(a);check.setButtonTintList(ColorStateList.valueOf(green));addView(check,new LinearLayout.LayoutParams(dp(48),dp(48)));check.setOnCheckedChangeListener((v,on)->{if(updatingChecks||song==null)return;if(on)selected.add(song.key);else selected.remove(song.key);updateSelection();});entry=row();entry.setMinimumHeight(dp(72));cover=new ArtworkView(a,false);cover.setImportantForAccessibility(View.IMPORTANT_FOR_ACCESSIBILITY_NO);entry.addView(cover,new LinearLayout.LayoutParams(dp(48),dp(48)));gap(entry,10);LinearLayout copy=column();title=text("",16,ink,false);oneLine(title);copy.addView(title);space(copy,5);LinearLayout metadata=row();artist=text("",12,muted,false);oneLine(artist);weight(metadata,artist);origin=text("",10,green,false);oneLine(origin);origin.setMaxWidth(dp(86));origin.setPadding(dp(6),dp(2),dp(6),dp(2));origin.setBackground(shape(0xffe9eee7,5));gap(metadata,6);metadata.addView(origin);copy.addView(metadata);weight(entry,copy);entry.setOnClickListener(v->{if(selecting&&favorites){if(!selected.add(song.key))selected.remove(song.key);updateSelection();}else PlaybackUi.play(a,repo,song,queue);});weight(this,entry);more=icon(R.drawable.player_more,"更多操作",()->menu(song,favorites,recent));addView(more);}
  void selection(){boolean on=selecting&&selected.contains(song.key);check.setChecked(on);setSelected(on);setBackground(ripple(on?0xffe3eee5:Color.TRANSPARENT,12));}
 }
 private View libraryRow(Song song,List<Song> queue,boolean favorites,boolean recent,View recycled){LibrarySongRow row=recycled instanceof LibrarySongRow?(LibrarySongRow)recycled:new LibrarySongRow();row.song=song;row.queue=queue;row.favorites=favorites;row.recent=recent;row.setTag(song);row.check.setVisibility(selecting&&favorites?View.VISIBLE:View.GONE);row.more.setVisibility(selecting?View.GONE:View.VISIBLE);updatingChecks=true;row.selection();updatingChecks=false;row.check.setContentDescription("选择 "+song.title);row.cover.bind(song);row.title.setText(song.title);row.artist.setText(song.artist.isEmpty()?"未知歌手":song.artist);Route fixed=song.fixedRoute();String origin=fixed!=null?fixed.sourceName:recent&&!song.routes.isEmpty()?song.routes.get(0).sourceName:"待选来源";row.origin.setText(SongText.clean(origin));row.entry.setContentDescription((selecting?"选择 ":"播放 ")+song.title+"，"+song.artist+"，"+origin);row.more.setContentDescription(song.title+" 的更多操作");return row;}
 private void empty(LinearLayout host,int drawable,String title,String subtitle,String action,Runnable run){LinearLayout box=column();box.setGravity(Gravity.CENTER);box.setPadding(dp(16),dp(30),dp(16),dp(26));box.addView(badge(drawable,56,0xffe9eee7,0xff7d9685));space(box,16);TextView heading=text(title,16,ink,true);heading.setGravity(Gravity.CENTER);box.addView(heading);space(box,8);TextView message=text(subtitle,13,muted,false);message.setGravity(Gravity.CENTER);message.setLineSpacing(dp(4),1);box.addView(message);if(action!=null){space(box,12);box.addView(button(action,run));}host.addView(box,new LinearLayout.LayoutParams(-1,-2));}
 private void playlistMenu(LibraryState.Playlist p){new UiSheet.Builder(a).setTitle(p.name).setItems(new String[]{"重命名","删除歌单"},(d,w)->{if(w==0)name(p.id,null);else confirm("删除歌单“"+p.name+"”？",()->{repo.editLibrary(l->l.playlists.removeIf(v->v.id.equals(p.id)),(ok,error)->{if(ok){if(page.equals(p.id))open("home");else redraw.run();}});});}).show();}
 private void open(String value){page=value;filter="";selecting=false;selected.clear();redraw.run();}
 private void menu(Song song,boolean favorites,boolean recent){List<String> items=new ArrayList<>(Arrays.asList("下一首播放","添加到队尾"));if(favorites){items.add("添加到歌单");items.add("选择收藏来源");items.add("取消收藏");}else if(!recent)items.add("移出歌单");else items.add(repo.liked(song)?"取消收藏":"收藏歌曲");new UiSheet.Builder(a).setTitle(song.title).setItems(items.toArray(new String[0]),(d,w)->{PlaybackService p=PlaybackService.instance;if(w<2){if(p!=null)p.enqueue(song,w==0);return;}if(favorites){if(w==2)addToPlaylist(Arrays.asList(song));else if(w==3)PlaybackUi.chooseRoute(a,repo,song,r->repo.pinFavorite(song,r));else repo.favorite(song,null);}else if(!recent){String playlistId=page;confirm("从歌单移除这首歌？",()->repo.editLibrary(l->{LibraryState.Playlist target=l.playlist(playlistId);if(target!=null)target.songs.removeIf(v->v.key.equals(song.key));}));}else PlaybackUi.favorite(a,repo,song);}).show();}
 private void addToPlaylist(List<Song> songs){if(songs.isEmpty())return;for(Song song:songs)if(song.fixedRoute()==null||song.sourceChoiceRequired){PlaybackUi.toast(a,"请先在收藏歌曲菜单选择固定来源，再添加到歌单");return;}List<LibraryState.Playlist> lists=new ArrayList<>(repo.library.playlists);String[] labels=new String[lists.size()+1];for(int i=0;i<lists.size();i++)labels[i]=lists.get(i).name;labels[lists.size()]="＋ 新建歌单";new UiSheet.Builder(a).setTitle("添加 "+songs.size()+" 首到歌单").setSingleChoiceItems(labels,-1,(d,w)->{if(w==lists.size())name(null,songs);else commitBatch(lists.get(w).id,songs);}).setNegativeButton("取消",null).show();}
 private void commitBatch(String id,List<Song> songs){int[] count={0};repo.editLibrary(l->count[0]=l.addToPlaylist(id,songs),(ok,error)->{if(ok){selecting=false;selected.clear();PlaybackUi.toast(a,"新增 "+count[0]+" 首，跳过重复 "+(songs.size()-count[0])+" 首");redraw.run();}});}
 private void name(String id,List<Song> songs){
  LinearLayout form=column();form.addView(text("歌单名称",13,muted,false));space(form,8);EditText input=new EditText(a);input.setSingleLine(true);input.setHint("例如：下班路上");input.setFilters(new InputFilter[]{new InputFilter.LengthFilter(60)});input.setImeOptions(android.view.inputmethod.EditorInfo.IME_ACTION_DONE);UiSheet.styleInput(input);if(id!=null&&repo.library.playlist(id)!=null)input.setText(repo.library.playlist(id).name);form.addView(input,new LinearLayout.LayoutParams(-1,-2));space(form,6);TextView error=text("",12,0xffb94e47,false);form.addView(error);form.addView(text("最多 60 个字符",12,muted,false));
  UiSheet dialog=new UiSheet.Builder(a).setTitle(id==null?"新建歌单":"重命名歌单").setView(form).setPositiveButton(id==null?"创建歌单":"保存名称",null).setNegativeButton("取消",null).create();
  dialog.setOnShowListener(d->{Button save=dialog.getButton(-1);Runnable validate=()->{String value=input.getText().toString().trim();boolean duplicate=repo.library.playlists.stream().anyMatch(p->!p.id.equals(id)&&p.name.equalsIgnoreCase(value));error.setText(duplicate?"已有同名歌单，换个名字试试":"");boolean valid=!value.isEmpty()&&!duplicate;save.setEnabled(valid);save.setAlpha(valid?1:.4f);};validate.run();input.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int after){}public void onTextChanged(CharSequence s,int st,int before,int count){validate.run();}public void afterTextChanged(Editable e){}});
   save.setOnClickListener(v->{String requestedName=input.getText().toString();save.setEnabled(false);input.setEnabled(false);int[] count={0};repo.editLibrary(l->{if(id!=null)l.rename(id,requestedName);else{LibraryState.Playlist p=l.create(requestedName);if(songs!=null)count[0]=l.addToPlaylist(p.id,songs);}},(ok,problem)->{if(a.isDestroyed())return;if(ok){dialog.dismiss();if(songs!=null){selecting=false;selected.clear();PlaybackUi.toast(a,"已添加 "+count[0]+" 首");}redraw.run();}else{input.setEnabled(true);validate.run();error.setText(problem);}});});input.setOnEditorActionListener((v,action,event)->{if(action==android.view.inputmethod.EditorInfo.IME_ACTION_DONE){if(save.isEnabled())save.performClick();return true;}return false;});input.requestFocus();input.setSelection(input.length());input.postDelayed(()->{if(dialog.isShowing())((android.view.inputmethod.InputMethodManager)a.getSystemService(android.content.Context.INPUT_METHOD_SERVICE)).showSoftInput(input,android.view.inputmethod.InputMethodManager.SHOW_IMPLICIT);},150);
  });dialog.show();
 }
 private void confirm(String title,Runnable run){new UiSheet.Builder(a).setTitle(title).setPositiveButton(title.contains("删除歌单")?"删除歌单":title.contains("移除")?"移出歌单":"确定",(d,w)->run.run()).setNegativeButton("取消",null).show();}
}
