package app.qingting.music;
import org.json.*;import java.util.*;import java.text.Collator;import static app.qingting.music.Models.*;
/** Pure local model. The Android adapter commits a staged copy before publishing. */
public final class LibraryState {
 public static final String[] SORTS={"默认顺序","添加时间 · 最新","添加时间 · 最早","歌名","歌手"};
 public final List<Song> favorites=new ArrayList<>();public final List<Playlist> playlists=new ArrayList<>();public final List<String> history=new ArrayList<>();
 public static final class Playlist {public String id,name;public long createdAt;public final List<Song> songs=new ArrayList<>();}
 public Playlist playlist(String id){for(Playlist p:playlists)if(p.id.equals(id))return p;return null;}
 private String name(String value,String except){String n=value.trim();if(n.isEmpty()||n.length()>60)throw new IllegalArgumentException("歌单名称需为 1–60 个字符");for(Playlist p:playlists)if(!p.id.equals(except)&&p.name.equalsIgnoreCase(n))throw new IllegalArgumentException("已有同名歌单");return n;}
 public Playlist create(String value){Playlist p=new Playlist();p.name=name(value,"");p.id=UUID.randomUUID().toString();p.createdAt=System.currentTimeMillis();playlists.add(p);return p;}
 public void rename(String id,String value){Playlist p=playlist(id);if(p==null)throw new IllegalArgumentException("歌单不存在");p.name=name(value,id);}
 public int addToPlaylist(String id,List<Song> songs){Playlist p=playlist(id);if(p==null)throw new IllegalArgumentException("歌单不存在");List<Song> additions=new ArrayList<>();Set<String> keys=new HashSet<>();for(Song s:p.songs)keys.add(s.key);for(Song s:songs){if(s.sourceChoiceRequired||s.fixedRoute()==null)throw new IllegalArgumentException("请先为旧收藏选择固定来源，再批量添加");if(keys.add(s.key)){Song copy=s.snapshot(s.fixedRoute());copy.addedAt=System.currentTimeMillis();additions.add(copy);}}p.songs.addAll(additions);return additions.size();}
 public void remember(String input){String q=input.trim();if(q.isEmpty())return;history.removeIf(v->v.equalsIgnoreCase(q));history.add(0,q);while(history.size()>30)history.remove(history.size()-1);}
 public static List<Song> filtered(List<Song> songs,String query,int sort){String q=query.trim().toLowerCase(Locale.ROOT);List<Song> result=new ArrayList<>();for(Song s:songs)if((s.title+" "+s.artist).toLowerCase(Locale.ROOT).contains(q))result.add(s);Collator c=Collator.getInstance(Locale.CHINA);if(sort==1||sort==2){boolean known=true;for(Song s:result)if(s.addedAt==0)known=false;if(known)result.sort((x,y)->Long.compare(x.addedAt,y.addedAt)*(sort==1?-1:1));}else if(sort==3)result.sort((x,y)->c.compare(x.title,y.title));else if(sort==4)result.sort((x,y)->c.compare(x.artist,y.artist));return result;}
 public static JSONArray songsJson(List<Song> songs)throws JSONException{JSONArray a=new JSONArray();for(Song s:songs)a.put(s.json());return a;}
 public static void readSongs(JSONArray a,List<Song> into){if(a==null)return;for(int i=0;i<a.length();i++)try{Song s=Song.from(a.getJSONObject(i));if(s!=null)into.add(s);}catch(Exception ignored){}}
 public JSONObject json()throws JSONException{JSONArray lists=new JSONArray();for(Playlist p:playlists)lists.put(new JSONObject().put("id",p.id).put("name",p.name).put("createdAt",p.createdAt).put("songs",songsJson(p.songs)));return new JSONObject().put("version",1).put("favorites",songsJson(favorites)).put("playlists",lists).put("history",new JSONArray(history));}
 public static LibraryState migrateLegacy(JSONArray values){LibraryState l=new LibraryState();readSongs(values,l.favorites);for(Song song:l.favorites){if(song.routes.size()==1){song.pinnedSource=song.routes.get(0).sourceId;song.pinnedRaw=song.routes.get(0).raw.toString();}else song.sourceChoiceRequired=true;}return l;}
 public static LibraryState from(JSONObject j){LibraryState l=new LibraryState();readSongs(j.optJSONArray("favorites"),l.favorites);JSONArray a=j.optJSONArray("playlists");if(a!=null)for(int i=0;i<a.length();i++)try{JSONObject v=a.getJSONObject(i);Playlist p=new Playlist();p.id=v.getString("id");p.name=v.getString("name");p.createdAt=v.optLong("createdAt");readSongs(v.optJSONArray("songs"),p.songs);l.playlists.add(p);}catch(Exception ignored){}a=j.optJSONArray("history");if(a!=null)for(int i=a.length()-1;i>=0;i--)if(a.opt(i) instanceof String)l.remember(a.optString(i));return l;}
}
