package app.qingting.music;
import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.*;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import androidx.media3.session.*;
import androidx.media3.session.MediaController;
import com.google.common.util.concurrent.ListenableFuture;
import org.json.*;
import java.util.*;
import static app.qingting.music.Models.*;

@androidx.media3.common.util.UnstableApi
public final class MainActivity extends Activity implements MusicRepository.Listener {
    private final int bg=Color.rgb(247,248,244),ink=Color.rgb(28,46,39),green=Color.rgb(36,94,79),muted=Color.rgb(111,123,114),line=Color.rgb(225,231,222);
    private String resultSignature="",chartSignature="";private LibraryUi libraryUi;private LibraryState shownLibrary;private List<Song> shownRecent=new ArrayList<>();private String renderedLibrary="";private ProgressBar miniProgress;private ArtworkView miniCover;
    private MusicRepository repo;private LinearLayout root,content,mini,nav;private EditText searchInput;private SongListView scroll;private int tab=1;private boolean editingHistory;
    private TextView miniTitle,miniStatus;private ImageButton miniButton;private LinearLayout batchDock;private boolean showFailed=false,renderQueued,started;private String renderedQuery="",renderedChart="";private int renderPass;
    private final Map<String,Integer> chartScrollOffsets=new HashMap<>();
    private final Handler handler=new Handler(Looper.getMainLooper());private ListenableFuture<MediaController> controllerFuture;
    private final Runnable visibleCheck=()->checkVisibleSongs();
    private final Runnable tick=new Runnable(){public void run(){updateMiniProgress();handler.postDelayed(this,250);}};
    @Override public void onCreate(Bundle state){
        super.onCreate(state);repo=((MusicApp)getApplication()).repository;repo.addListener(this);libraryUi=new LibraryUi(this,repo,this::renderContent);libraryUi.restore(state);
        if(state!=null){tab=state.getInt("tab",1);editingHistory=state.getBoolean("editingHistory");}
        root=column();root.setBackgroundColor(bg);root.setPadding(dp(20),0,dp(20),0);setContentView(root);
        root.setOnApplyWindowInsetsListener((v,insets)->{
            if(Build.VERSION.SDK_INT>=30){android.graphics.Insets i=insets.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.ime());v.setPadding(dp(20),i.top,dp(20),i.bottom);}
            else v.setPadding(dp(20),insets.getSystemWindowInsetTop(),dp(20),insets.getSystemWindowInsetBottom());return insets;
        });
        controllerFuture=new MediaController.Builder(this,new SessionToken(this,new ComponentName(this,PlaybackService.class))).buildAsync();
        controllerFuture.addListener(this::updateMini,command->handler.post(command));build();repo.ensureDefaultSubscriptions();
    }
    @Override protected void onStart(){super.onStart();if(repo==null)return;started=true;handler.post(tick);scheduleVisibleChecks();if(tab==1)repo.ensureCharts();}
    @Override protected void onStop(){started=false;handler.removeCallbacks(tick);handler.removeCallbacks(visibleCheck);if(repo!=null)repo.cancelVisibleChecks();super.onStop();}
    @Override protected void onSaveInstanceState(Bundle out){super.onSaveInstanceState(out);out.putInt("tab",tab);out.putBoolean("editingHistory",editingHistory);libraryUi.save(out);}
    @Override protected void onDestroy(){if(repo!=null)repo.removeListener(this);handler.removeCallbacksAndMessages(null);if(controllerFuture!=null)MediaController.releaseFuture(controllerFuture);super.onDestroy();}
    @Override public void changed(){if(renderQueued)return;renderQueued=true;handler.postDelayed(()->{renderQueued=false;if(tab!=2||shownLibrary!=repo.library||!shownRecent.equals(repo.recent))renderContent();updateRowStates();updateMini();},100);}
    private int dp(float n){return (int)(getResources().getDisplayMetrics().density*n+0.5f);}
    private LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
    private GradientDrawable shape(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    private TextView text(String value,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
    private TextView button(String label,boolean primary,Runnable action){TextView b=text(label,14,primary?Color.WHITE:green,true);b.setGravity(Gravity.CENTER);b.setMinHeight(dp(48));b.setPadding(dp(14),dp(8),dp(14),dp(8));b.setBackground(shape(primary?green:Color.rgb(233,239,231),14));b.setOnClickListener(v->action.run());b.setContentDescription(label);return b;}
    private void space(LinearLayout l,int height){View v=new View(this);l.addView(v,new LinearLayout.LayoutParams(1,dp(height)));}
    private void weighted(LinearLayout l,View v){l.addView(v,new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1));}
    private void gap(LinearLayout l){l.addView(new View(this),new LinearLayout.LayoutParams(dp(8),1));}
    private LinearLayout card(){LinearLayout c=column();c.setPadding(dp(16),dp(16),dp(16),dp(16));c.setBackground(shape(Color.WHITE,20));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(12);c.setLayoutParams(p);return c;}
    private void build(){
        resultSignature="";chartSignature="";
        root.removeAllViews();space(root,8);
        if(tab==0){LinearLayout search=row();searchInput=new EditText(this);searchInput.setSingleLine(true);searchInput.setTextSize(16);searchInput.setHint("搜索歌曲、歌手");searchInput.setText(repo.query);searchInput.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int start,int count,int after){}public void onTextChanged(CharSequence s,int start,int before,int count){if(s.length()==0&&!repo.query.isEmpty())repo.search("");}public void afterTextChanged(android.text.Editable e){}});searchInput.setPadding(dp(14),dp(8),dp(10),dp(8));searchInput.setBackground(shape(Color.WHITE,14));searchInput.setImeOptions(android.view.inputmethod.EditorInfo.IME_ACTION_SEARCH);weighted(search,searchInput);gap(search);search.addView(button("搜索",true,this::search));searchInput.setOnEditorActionListener((v,id,e)->{search();return true;});root.addView(search);space(root,10);}
        scroll=new SongListView(this);scroll.setClipToPadding(false);content=scroll.header;content.setPadding(0,dp(8),0,dp(8));scroll.setOnScrollListener(new AbsListView.OnScrollListener(){public void onScrollStateChanged(AbsListView v,int state){scheduleVisibleChecks();}public void onScroll(AbsListView v,int first,int visible,int total){scheduleVisibleChecks();}});root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));libraryUi.attachList(scroll);
        batchDock=column();batchDock.setVisibility(View.GONE);root.addView(batchDock);libraryUi.attachDock(batchDock);
        mini=column();mini.setBackground(shape(0xffe9eee7,14));mini.setPadding(dp(8),dp(4),dp(6),dp(4));LinearLayout m=row();miniCover=new ArtworkView(this,false);m.addView(miniCover,new LinearLayout.LayoutParams(dp(40),dp(40)));gap(m);LinearLayout titles=column();miniTitle=text("选择一首歌，开始听",14,ink,true);miniTitle.setSingleLine(true);miniTitle.setEllipsize(android.text.TextUtils.TruncateAt.END);miniStatus=text("搜索 · 收藏 · 我的歌单",11,muted,false);miniStatus.setSingleLine(true);miniStatus.setEllipsize(android.text.TextUtils.TruncateAt.END);titles.addView(miniTitle);space(titles,3);titles.addView(miniStatus);weighted(m,titles);miniButton=compactIcon(R.drawable.player_play,"播放",()->{if(PlaybackService.instance!=null)PlaybackService.instance.toggle();});m.addView(miniButton);m.addView(compactIcon(R.drawable.library_playlist,"当前播放列表",()->PlaybackUi.queue(this)));mini.addView(m);miniProgress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);miniProgress.setProgressTintList(android.content.res.ColorStateList.valueOf(green));miniProgress.setMax(1000);mini.addView(miniProgress,new LinearLayout.LayoutParams(-1,dp(2)));miniCover.setOnClickListener(v->openPlayer());titles.setOnClickListener(v->openPlayer());root.addView(mini);
        nav=row();nav.setPadding(0,dp(4),0,0);String[] labels={"排行榜","搜索","我的","订阅源"};int[] tabs={1,0,2,3},icons={R.drawable.ui_charts,R.drawable.library_search,R.drawable.ui_user,R.drawable.ui_sources};for(int i=0;i<labels.length;i++){final int n=tabs[i];LinearLayout item=column();item.setGravity(Gravity.CENTER);item.setMinimumHeight(dp(52));ImageView mark=new ImageView(this);mark.setImageResource(icons[i]);mark.setImageTintList(android.content.res.ColorStateList.valueOf(tab==n?green:muted));item.addView(mark,new LinearLayout.LayoutParams(dp(24),dp(24)));mark.setImportantForAccessibility(View.IMPORTANT_FOR_ACCESSIBILITY_NO);item.setTooltipText(labels[i]);item.setSelected(tab==n);item.setContentDescription(labels[i]+(tab==n?"，当前页面":""));item.setBackground(new android.graphics.drawable.RippleDrawable(android.content.res.ColorStateList.valueOf(0x18245e4f),shape(tab==n?0xffedf2e9:Color.TRANSPARENT,12),null));item.setOnClickListener(v->{if(tab==n)return;repo.cancelVisibleChecks();libraryUi.leaveSelection();editingHistory=false;tab=n;build();if(n==1)repo.ensureCharts();});nav.addView(item,new LinearLayout.LayoutParams(0,dp(52),1));}root.addView(nav);renderContent();updateMini();
    }
    private ImageButton compactIcon(int drawable,String description,Runnable action){ImageButton button=new ImageButton(this);button.setImageResource(drawable);button.setContentDescription(description);button.setImageTintList(android.content.res.ColorStateList.valueOf(green));button.setPadding(dp(12),dp(12),dp(12),dp(12));button.setBackground(new android.graphics.drawable.RippleDrawable(android.content.res.ColorStateList.valueOf(0x18245e4f),shape(Color.TRANSPARENT,24),null));button.setLayoutParams(new LinearLayout.LayoutParams(dp(48),dp(48)));button.setOnClickListener(v->action.run());return button;}
    @Override public void onBackPressed(){if(tab==2&&libraryUi.handleBack())return;if(editingHistory){editingHistory=false;renderContent();return;}super.onBackPressed();}
    private void search(){editingHistory=false;String q=searchInput.getText().toString();repo.search(q);((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(searchInput.getWindowToken(),0);searchInput.clearFocus();}
    private void renderContent(){
        if(tab==1&&content!=null){String signature=chartStructure();if(signature.equals(chartSignature)){updateRowStates();return;}chartSignature=signature;}else chartSignature="";
        if(content==null)return;if(tab==0&&!repo.query.isEmpty()){StringBuilder signature=new StringBuilder(repo.query+":"+repo.onlyPlayable+":"+repo.searching+":"+repo.scanningResults);for(Song song:visibleResults(repo.results))signature.append('|').append(song.key);if(signature.toString().equals(resultSignature)){updateRowStates();return;}resultSignature=signature.toString();}else resultSignature="";int position=scroll.getFirstVisiblePosition(),offset=scroll.getChildCount()==0?0:scroll.getChildAt(0).getTop();String anchor=scroll.getChildCount()>0&&scroll.getChildAt(0).getTag() instanceof Song?((Song)scroll.getChildAt(0).getTag()).key:null;
        String chart=tab==1&&repo.charts.current!=null?repo.charts.current.sourceId+":"+repo.charts.current.raw.optString("id"):"";
        String library=tab==2?libraryUi.pageKey():"";if(!renderedQuery.equals(repo.query)||!renderedChart.equals(chart)||!renderedLibrary.equals(library)){renderedQuery=repo.query;renderedChart=chart;renderedLibrary=library;position=0;offset=0;anchor=null;}
        content.removeAllViews();scroll.footer.removeAllViews();scroll.songs(Collections.emptyList(),0,(song,recycled,parent)->recycled);if(batchDock!=null){batchDock.removeAllViews();batchDock.setVisibility(View.GONE);}if(tab==0)searchPage();else if(tab==1)chartsPage();else if(tab==2)libraryPage();else sourcesPage();
        int pass=++renderPass,target=position,top=offset;String key=anchor;scroll.post(()->{if(pass!=renderPass)return;int found=key==null?-1:scroll.positionOf(key);scroll.setSelectionFromTop(found>=0?found:target,top);scheduleVisibleChecks();});
    }
    private void scheduleVisibleChecks(){handler.removeCallbacks(visibleCheck);if(started)handler.postDelayed(visibleCheck,250);}
    private void checkVisibleSongs(){
        if(!started||scroll==null)return;List<Song> visible=new ArrayList<>();for(View row:scroll.songRows())visible.add((Song)row.getTag());
        repo.verifyVisible(visible);
    }
    private void section(String title,String subtitle){content.addView(text(title,23,ink,true));space(content,5);content.addView(text(subtitle,12,muted,false));space(content,18);}
    private void empty(String symbol,String title,String description,String action,Runnable callback){LinearLayout c=card();c.setPadding(dp(24),dp(30),dp(24),dp(30));c.addView(text(symbol,42,green,true));space(c,20);c.addView(text(title,21,ink,true));space(c,10);TextView copy=text(description,14,muted,false);copy.setLineSpacing(dp(4),1);c.addView(copy);space(c,22);if(action!=null)c.addView(button(action,true,callback));content.addView(c);}
    private void searchPage(){
        if(repo.query.isEmpty()){searchHistory();return;}
        LinearLayout top=row();weighted(top,text("搜索结果",22,ink,true));top.addView(text(repo.results.size()+" 首"+(repo.searching?" · 搜索中":""),12,muted,false));content.addView(top);space(content,12);
        LinearLayout filters=row();weighted(filters,button(repo.onlyPlayable?"仅看已验证":"可播优先 · 全部结果",false,()->{repo.onlyPlayable=!repo.onlyPlayable;renderContent();}));gap(filters);filters.addView(button("来源状态",false,this::searchSourceStatus));content.addView(filters);space(content,8);
        content.addView(text(repo.scanningResults?repo.resultScanStatus:"自动试播当前可见歌曲 · 优先准确匹配和已验证线路",11,muted,false));space(content,14);
        List<Song> results=visibleResults(repo.results);int shown=results.size();scroll.songs(results,0,(song,recycled,parent)->songCard(song,repo.results,0,recycled));
        if(shown==0&&!repo.searching)empty("⌕",repo.onlyPlayable?"暂时没有试播通过的结果":"暂时没有匹配结果",repo.onlyPlayable?"切回全部结果，自动检查会继续；也可以直接尝试播放。":"换个关键词，或查看订阅源连接状态。",repo.onlyPlayable?"查看全部":null,()->{repo.onlyPlayable=false;renderContent();});
        if(repo.hasMore()&&!repo.searching)scroll.footer.addView(button("加载更多结果",false,repo::loadMore));
    }
    private TextView historyAction(String label,Runnable action){
        TextView view=text(label,13,muted,false);view.setGravity(Gravity.CENTER);view.setMinWidth(dp(48));view.setMinHeight(dp(48));view.setPadding(dp(8),0,dp(8),0);
        view.setBackground(new android.graphics.drawable.RippleDrawable(android.content.res.ColorStateList.valueOf(0x18245e4f),null,shape(Color.WHITE,12)));view.setOnClickListener(v->action.run());return view;
    }
    private void searchHistory(){
        List<String> history=new ArrayList<>(repo.library.history);if(history.isEmpty())editingHistory=false;
        LinearLayout head=row();weighted(head,text("最近搜索",17,ink,true));
        if(!history.isEmpty()){
            if(editingHistory)head.addView(historyAction("清空",()->new UiSheet.Builder(this).setTitle("清空搜索历史？").setMessage("清空后无法恢复。").setPositiveButton("清空",(d,w)->{repo.editLibrary(l->l.history.clear(),(ok,error)->{if(ok){editingHistory=false;renderContent();}});}).setNegativeButton("取消",null).show()));
            head.addView(historyAction(editingHistory?"完成":"管理",()->{editingHistory=!editingHistory;renderContent();}));
        }else head.setMinimumHeight(dp(48));
        content.addView(head);
        if(history.isEmpty()){space(content,8);content.addView(text("搜一首喜欢的歌，最近搜索会留在这里",13,muted,false));return;}
        HistoryTags tags=new HistoryTags();
        for(String query:history){
            LinearLayout chip=row();chip.setGravity(Gravity.CENTER_VERTICAL);chip.setMinimumWidth(dp(48));chip.setMinimumHeight(dp(48));
            android.graphics.drawable.RippleDrawable fill=new android.graphics.drawable.RippleDrawable(android.content.res.ColorStateList.valueOf(0x18245e4f),shape(0xffecefe9,18),null);
            chip.setBackground(new android.graphics.drawable.InsetDrawable(fill,0,dp(6),0,dp(6)));chip.setPadding(dp(14),dp(6),dp(editingHistory?10:14),dp(6));
            TextView label=text(query,14,ink,false);label.setSingleLine(true);label.setEllipsize(android.text.TextUtils.TruncateAt.END);chip.addView(label,new LinearLayout.LayoutParams(-2,-2,1));
            if(editingHistory){TextView remove=text("×",18,muted,false);remove.setPadding(dp(8),0,0,0);remove.setImportantForAccessibility(View.IMPORTANT_FOR_ACCESSIBILITY_NO);chip.addView(remove);}
            label.setImportantForAccessibility(View.IMPORTANT_FOR_ACCESSIBILITY_NO);chip.setFocusable(true);chip.setContentDescription((editingHistory?"删除搜索记录：":"搜索：")+query);
            chip.setOnClickListener(v->{if(editingHistory){repo.editLibrary(l->l.history.remove(query));}else{searchInput.setText(query);search();}});
            chip.setOnLongClickListener(v->{if(editingHistory)return false;editingHistory=true;renderContent();return true;});tags.addView(chip);
        }
        content.addView(tags,new LinearLayout.LayoutParams(-1,-2));
    }
    /** Wrap compact history tags using the actual available width, including after rotation. */
    private final class HistoryTags extends ViewGroup {
        HistoryTags(){super(MainActivity.this);}
        @Override protected void onMeasure(int widthSpec,int heightSpec){
            int width=MeasureSpec.getSize(widthSpec),limit=Math.max(0,width-getPaddingLeft()-getPaddingRight()),x=0,y=0,rowHeight=0;
            for(int i=0;i<getChildCount();i++){View child=getChildAt(i);child.measure(MeasureSpec.makeMeasureSpec(limit,MeasureSpec.AT_MOST),MeasureSpec.makeMeasureSpec(0,MeasureSpec.UNSPECIFIED));int w=child.getMeasuredWidth(),h=child.getMeasuredHeight();if(x>0&&x+w>limit){y+=rowHeight;x=0;rowHeight=0;}x+=w+dp(8);rowHeight=Math.max(rowHeight,h);}
            setMeasuredDimension(resolveSize(width,widthSpec),resolveSize(getPaddingTop()+y+rowHeight+getPaddingBottom(),heightSpec));
        }
        @Override protected void onLayout(boolean changed,int left,int top,int right,int bottom){
            int limit=right-left-getPaddingLeft()-getPaddingRight(),x=0,y=getPaddingTop(),rowHeight=0;boolean rtl=getLayoutDirection()==View.LAYOUT_DIRECTION_RTL;
            for(int i=0;i<getChildCount();i++){View child=getChildAt(i);int w=child.getMeasuredWidth(),h=child.getMeasuredHeight();if(x>0&&x+w>limit){y+=rowHeight;x=0;rowHeight=0;}int start=getPaddingLeft()+(rtl?limit-x-w:x);child.layout(start,y,start+w,y+h);x+=w+dp(8);rowHeight=Math.max(rowHeight,h);}
        }
        @Override protected ViewGroup.LayoutParams generateDefaultLayoutParams(){return new ViewGroup.LayoutParams(-2,-2);}
    }
    private void searchSourceStatus(){new UiSheet.Builder(this).setTitle("搜索来源状态").setMessage(repo.searchStates.isEmpty()?"暂无来源状态":String.join("\n\n",repo.searchStates.values())).setPositiveButton("关闭",null).setNeutralButton(repo.scanningResults?"取消全量检测":"检测全部结果",(d,w)->{if(repo.scanningResults)repo.cancelResultScan();else if(repo.searching)toast("请等待本轮搜索完成");else repo.scanResults();}).show();}
    private final class MainSongRow extends LinearLayout {
        final TextView number,name,artist,sources,more;final ArtworkView cover;Song song;List<Song> queue;
        MainSongRow(){super(MainActivity.this);setOrientation(HORIZONTAL);setGravity(Gravity.CENTER_VERTICAL);setPadding(0,dp(6),0,dp(6));setMinimumHeight(dp(72));number=text("",14,muted,false);number.setGravity(Gravity.CENTER);addView(number,new LinearLayout.LayoutParams(dp(30),dp(48)));cover=new ArtworkView(MainActivity.this,false);addView(cover,new LinearLayout.LayoutParams(dp(48),dp(48)));gap(this);LinearLayout info=column();name=text("",16,ink,true);name.setSingleLine(true);name.setEllipsize(android.text.TextUtils.TruncateAt.END);artist=text("",12,muted,false);artist.setSingleLine(true);artist.setEllipsize(android.text.TextUtils.TruncateAt.END);info.addView(name);info.addView(artist);info.setMinimumHeight(dp(60));info.setGravity(Gravity.CENTER_VERTICAL);info.setOnClickListener(v->PlaybackUi.play(MainActivity.this,repo,song,visibleResults(queue)));weighted(this,info);sources=text("",12,green,false);sources.setTag("sourceCount");sources.setGravity(Gravity.CENTER);sources.setMinHeight(dp(48));sources.setPadding(dp(6),0,dp(6),0);sources.setOnClickListener(v->songRoutes(song,queue));addView(sources);more=text("⋮",24,muted,false);more.setGravity(Gravity.CENTER);addView(more,new LinearLayout.LayoutParams(dp(48),dp(48)));more.setOnClickListener(v->{Song selected=song;new UiSheet.Builder(MainActivity.this).setTitle(selected.title).setItems(new String[]{repo.liked(selected)?"取消收藏":"收藏歌曲","下一首播放","添加到队尾"},(d,w)->{if(w==0)PlaybackUi.favorite(MainActivity.this,repo,selected);else if(PlaybackService.instance!=null)PlaybackService.instance.enqueue(selected,w==1);}).show();});}
    }
    private View songCard(Song song,List<Song> queue,int rank,View recycled){MainSongRow item=recycled instanceof MainSongRow?(MainSongRow)recycled:new MainSongRow();item.song=song;item.queue=queue;item.setTag(song);item.number.setVisibility(rank>0?View.VISIBLE:View.GONE);item.number.setText(rank>0?String.format(Locale.ROOT,"%02d",rank):"");item.number.setTextColor(rank<4?green:muted);item.number.setTypeface(Typeface.DEFAULT,rank<4?Typeface.BOLD:Typeface.NORMAL);item.cover.bind(song);item.name.setText(song.title);item.artist.setText(song.artist+(SongPolicy.versionLabel(song).isEmpty()?"":" · "+SongPolicy.versionLabel(song)));item.sources.setContentDescription(song.title+" 的 "+song.routes.size()+" 个播放源");updateRowState(item);return item;}
    private List<Song> visibleResults(List<Song> original){if(original!=repo.results)return original;List<Song> visible=repo.sortedResults();if(repo.onlyPlayable)visible.removeIf(song->repo.playableCount(song)==0);return visible;}
    private void songRoutes(Song song,List<Song> queue){List<Route> routes=new ArrayList<>(song.routes);routes.sort(Comparator.comparingInt(r->repo.eligible(r)&&SongPolicy.recentlyPlayable(r,System.currentTimeMillis())?0:1));String[] labels=new String[routes.size()];for(int i=0;i<routes.size();i++){Route route=routes.get(i);Source source=repo.source(route.sourceId);labels[i]=SongText.clean(route.sourceName)+" · "+(source==null||!source.enabled?"已停用":source.hidden()?"已过滤":route.label());}new UiSheet.Builder(this).setTitle("播放时自动选线，失败自动补搜").setItems(labels,(d,w)->routeDialog(song,queue,routes.get(w))).setNeutralButton("重新检测",(d,w)->repo.verify(song)).setNegativeButton("关闭",null).show();}
    private void routeDialog(Song song,List<Song> queue,Route route){new UiSheet.Builder(this).setTitle(route.sourceName).setMessage("状态："+route.label()+(route.error.isEmpty()?"":"\n原因："+route.error)+"\n试播通过表示已短暂静音解码播放；链路可达仅表示响应正常。").setPositiveButton("用此线路播放",(d,w)->play(song,queue,route)).setNeutralButton("重新检测",(d,w)->repo.deepVerify(route,()->true,(m,e)->{})).setNegativeButton("关闭",null).show();}
    private String chartStructure(){Charts c=repo.charts;DailyCharts d=repo.dailyCharts;StringBuilder out=new StringBuilder();out.append(c.token()).append('|').append(c.page).append('|').append(c.songs.size()).append('|').append(c.end).append('|').append(c.loadingSongs).append('|').append(c.loadingCatalog).append('|').append(c.detailStatus).append('|').append(repo.filteringCharts).append('|').append(repo.chartFilterStatus).append('|').append(repo.isAutomaticChart()).append('|').append(d.loading).append('|').append(d.status).append('|').append(d.fetchedAt);for(Charts.Board b:availableBoards())out.append('|').append(System.identityHashCode(b));return out.toString();}
    private void chartsPage(){
        Charts charts=repo.charts;DailyCharts daily=repo.dailyCharts;
        LinearLayout heading=row();weighted(heading,text("排行榜",24,ink,true));heading.addView(historyAction(repo.filteringCharts?"取消刷新":"刷新榜单",repo::refreshAndFilterCharts));heading.addView(historyAction("管理",this::chartOptions));content.addView(heading);if(!repo.chartFilterStatus.isEmpty()){TextView status=text(repo.chartFilterStatus+"  ›",12,muted,false);status.setSingleLine(true);status.setEllipsize(android.text.TextUtils.TruncateAt.END);status.setMinHeight(dp(40));status.setGravity(Gravity.CENTER_VERTICAL);status.setOnClickListener(v->new UiSheet.Builder(this).setTitle("榜单刷新详情").setMessage(repo.chartFilterStatus+"\n\n"+String.join("\n\n",repo.charts.sourceStates.values())).setPositiveButton("关闭",null).show());content.addView(status);space(content,6);}space(content,10);
        List<Charts.Board> boards=availableBoards();LinkedHashMap<String,Charts.Board> sources=new LinkedHashMap<>();for(Charts.Board b:boards)sources.putIfAbsent(b.sourceId,b);
        if(!sources.isEmpty()){LinearLayout choices=row();for(Charts.Board b:sources.values()){boolean active=charts.current!=null&&charts.current.sourceId.equals(b.sourceId);choices.addView(sourceChip(SongText.clean(b.sourceName),active,()->{if(!active)repo.openChart(b);else chooseChart(b.sourceId);}));gap(choices);}horizontalChoices(choices,"sources");space(content,10);}
        if(charts.current==null){empty("≋",charts.loadingCatalog?"正在读取排行榜":"还没有可用榜单",daily.loading?"正在自动检查榜单；目录出现后也可以直接选择。":"点刷新榜单重新检查，空榜及加载失败的榜单会隐藏，可在管理中查看原因并重新检查。",repo.filteringCharts?"取消刷新":"刷新榜单",repo::refreshAndFilterCharts);return;}
        Charts.Board board=charts.current;LinearLayout hero=column();hero.setPadding(dp(16),dp(12),dp(16),dp(12));hero.setBackground(shape(green,20));
        TextView eyebrow=text((repo.isAutomaticChart()?"自动选榜":"正在浏览")+(board.group.isEmpty()?"":"  /  "+SongText.clean(board.group)),11,Color.rgb(195,220,206),false);hero.addView(eyebrow);space(hero,6);
        LinearLayout titleRow=row();TextView title=text(SongText.clean(board.title),22,Color.WHITE,true);title.setMaxLines(2);weighted(titleRow,title);TextView change=text("切换 ▾",13,Color.WHITE,true);change.setGravity(Gravity.CENTER);change.setMinHeight(dp(48));change.setPadding(dp(12),0,0,0);change.setOnClickListener(v->chooseChart(board.sourceId));change.setContentDescription("切换排行榜");titleRow.addView(change);hero.addView(titleRow);
        long stamp=DailyCharts.timestamp(charts.detailRaw);boolean cached=repo.isAutomaticChart()&&daily.hasUsableSource()&&daily.current.sourceId.equals(board.sourceId)&&daily.current.raw.optString("id").equals(board.raw.optString("id"));
        if(stamp==0&&cached)stamp=daily.publishedAt;String info=charts.end?charts.songs.size()+" 首歌曲":"已加载 "+charts.songs.size()+" 首 · 支持继续加载";
        if(stamp>0)info+="  ·  更新 "+chartDate(stamp);else if(cached)info+="  ·  缓存 "+chartDate(daily.fetchedAt);
        hero.addView(text(info,11,Color.rgb(215,230,219),false));content.addView(hero);space(content,10);
        LinearLayout playbar=row();TextView all=button("▶ 播放全部",true,()->{if(!charts.songs.isEmpty())play(charts.songs.get(0),charts.songs,null);});all.setEnabled(!charts.songs.isEmpty());playbar.addView(all);gap(playbar);weighted(playbar,text("按原榜顺序\n失败自动换线路",11,muted,false));content.addView(playbar);space(content,8);
        if(charts.songs.isEmpty())content.addView(text(charts.loadingSongs?"正在加载歌曲…":charts.detailStatus.isEmpty()?"该榜单暂时没有歌曲":charts.detailStatus,13,muted,false));
        scroll.songs(charts.songs,0,(song,recycled,parent)->songCard(song,charts.songs,charts.rank(song),recycled));
        space(scroll.footer,10);if(!charts.songs.isEmpty())scroll.footer.addView(text(charts.detailStatus,11,muted,false));space(scroll.footer,8);
        if(!charts.end){TextView more=button(charts.loadingSongs?"正在加载…":charts.songs.isEmpty()?"重试加载":"加载更多歌曲",false,repo::loadMoreChart);more.setEnabled(!charts.loadingSongs);scroll.footer.addView(more);}else scroll.footer.addView(text("— 已展示本榜全部 "+charts.songs.size()+" 首 —",12,muted,false));
        if(repo.isAutomaticChart()){space(scroll.footer,10);scroll.footer.addView(text(daily.loading?"正在后台检查更新，当前榜单仍可浏览":daily.status,11,muted,false));}
    }
    private TextView sourceChip(String label,boolean selected,Runnable run){TextView chip=historyAction(label,run);chip.setTextColor(selected?green:muted);chip.setTypeface(android.graphics.Typeface.DEFAULT,selected?android.graphics.Typeface.BOLD:android.graphics.Typeface.NORMAL);chip.setBackground(shape(selected?0xffe1ebe0:Color.TRANSPARENT,12));return chip;}
    private String chartDate(long time){return new java.text.SimpleDateFormat("MM-dd HH:mm",Locale.CHINA).format(new Date(time));}
    private void horizontalChoices(LinearLayout choices,String key){HorizontalScrollView view=new HorizontalScrollView(this);view.setHorizontalScrollBarEnabled(false);view.addView(choices);content.addView(view);int position=chartScrollOffsets.getOrDefault(key,0);view.setOnScrollChangeListener((v,x,y,oldX,oldY)->chartScrollOffsets.put(key,x));view.post(()->view.scrollTo(position,0));}
    private List<Charts.Board> availableBoards(){List<Charts.Board> result=new ArrayList<>();for(Charts.Board b:repo.charts.boards){Source s=repo.source(b.sourceId);if(Charts.sourceAvailable(s)&&!repo.chartHidden(b))result.add(b);}Charts.Board current=repo.charts.current;if(current!=null){boolean found=false;for(Charts.Board b:result)if(b.sourceId.equals(current.sourceId)&&b.raw.optString("id").equals(current.raw.optString("id")))found=true;Source s=repo.source(current.sourceId);if(!found&&Charts.sourceAvailable(s)&&!repo.chartHidden(current))result.add(0,current);}return result;}
    private void chooseChart(String sourceId){List<Charts.Board> choices=new ArrayList<>();for(Charts.Board b:availableBoards())if(b.sourceId.equals(sourceId))choices.add(b);String[] names=new String[choices.size()];int checked=-1;for(int i=0;i<choices.size();i++){Charts.Board b=choices.get(i);names[i]=(b.group.isEmpty()?"":SongText.clean(b.group)+" · ")+SongText.clean(b.title);if(repo.charts.current!=null&&repo.charts.current.sourceId.equals(b.sourceId)&&repo.charts.current.raw.optString("id").equals(b.raw.optString("id")))checked=i;}new UiSheet.Builder(this).setTitle("选择排行榜 · "+choices.size()+" 个").setSingleChoiceItems(names,checked,(d,w)->{d.dismiss();repo.openChart(choices.get(w));}).setNegativeButton("关闭",null).show();}
    private void chartOptions(){new UiSheet.Builder(this).setTitle("排行榜").setItems(new String[]{"刷新当前榜单歌曲","自动选择可用榜单并更新缓存","刷新所有来源的榜单目录","查看来源状态","查看隐藏榜单及原因"},(d,w)->{if(w==0)repo.refreshCurrentChart();else if(w==1)repo.useDailyChart();else if(w==2)repo.refreshCharts();else if(w==4)new UiSheet.Builder(this).setTitle("隐藏榜单及原因").setMessage(repo.hiddenChartReport()).setPositiveButton("关闭",null).setNeutralButton("重新检查",(dialog,which)->repo.refreshAndFilterCharts()).show();else new UiSheet.Builder(this).setTitle("榜单来源状态").setMessage(repo.charts.sourceStates.isEmpty()?"尚未读取榜单目录":String.join("\n\n",repo.charts.sourceStates.values())).setPositiveButton("关闭",null).show();}).setNegativeButton("关闭",null).show();}
    private void libraryPage(){shownLibrary=repo.library;shownRecent=new ArrayList<>(repo.recent);libraryUi.render(content);}
    private void sourcesPage(){
        section("订阅源","兼容安卓版 MusicFree JS 插件订阅");content.addView(button("使用手册 · 如何添加和使用订阅",false,this::openHelp));space(content,12);LinearLayout buttons=row();weighted(buttons,button(repo.importing?"正在导入…":"＋ 添加订阅",true,this::importDialog));gap(buttons);weighted(buttons,button(repo.scanningSources?"取消检测":"一键过滤渠道",false,()->{if(repo.scanningSources)repo.cancelSourceScan();else repo.scanSources();}));content.addView(buttons);space(content,14);
        for(String url:MusicRepository.DEFAULT_SUBSCRIPTIONS){LinearLayout defaults=card();defaults.addView(text("默认订阅 · "+(url.contains("nairocy")?"Nairocy":"MusicFreePluginsHub"),15,ink,true));space(defaults,6);TextView address=text(url,11,muted,false);address.setTextIsSelectable(true);defaults.addView(address);space(defaults,8);defaults.addView(text(repo.defaultSubscriptionStatus(url),12,green,false));space(defaults,8);TextView retry=button("补导缺失插件 / 重试",false,()->repo.retryDefaultSubscription(url));retry.setEnabled(!repo.importing);retry.setAlpha(repo.importing?.5f:1);defaults.addView(retry);content.addView(defaults);}
        if(!repo.sourceScanStatus.isEmpty()){content.addView(text(repo.sourceScanStatus,13,green,false));space(content,12);}
        if(!repo.notice.isEmpty()){TextView notice=text(repo.notice,13,green,false);notice.setTextIsSelectable(true);content.addView(notice);space(content,12);}
        if(repo.sources.isEmpty())empty("≋","正在连接你的音乐来源","首次打开会导入上面的默认订阅；失败后可点重试，也可以添加自己的订阅。",null,null);
        for(Source s:repo.sources){LinearLayout c=card();LinearLayout title=row();weighted(title,text(s.name,18,ink,true));Switch enabled=new Switch(this);enabled.setContentDescription("启用 "+s.name);enabled.setChecked(s.enabled);enabled.setOnCheckedChangeListener((v,b)->{s.enabled=b;repo.save();});title.addView(enabled);c.addView(title);space(c,6);c.addView(text("v"+s.version+"  ·  "+(s.hidden()?"已过滤":s.enabled?"已启用":"已停用"),12,s.hidden()?Color.rgb(162,87,50):green,false));space(c,8);c.addView(text(s.music?s.playbackMessage:s.topLists?"支持排行榜":"歌词专用源 · 播放时自动匹配",13,muted,false));space(c,6);c.addView(text(s.message,12,muted,false));space(c,12);
            LinearLayout actions=row();weighted(actions,button(s.hidden()?"恢复":"复检",false,()->{if(s.hidden())repo.restore(s);else if(s.music)repo.scanSources(Collections.singletonList(s));else toast("歌词专用源会在播放时自动获取歌词");}));gap(actions);weighted(actions,button("配置",false,()->configDialog(s)));gap(actions);weighted(actions,button("更新",false,()->repo.importUrl(s.subscription.isEmpty()?s.url:s.subscription)));c.addView(actions);content.addView(c);}
        space(content,8);content.addView(text("每个音乐渠道抽检最多 3 首不同歌曲，均试播失败后过滤，可随时恢复。搜索失败临时过滤 15 分钟。离线不新增过滤；通过抽检不代表所有歌曲都能播放。",12,muted,false));
    }
    private void importDialog(){EditText input=new EditText(this);input.setHint("https://…/plugins.json");input.setSingleLine(true);input.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_URI);LinearLayout wrap=column();wrap.setPadding(dp(24),dp(10),dp(24),0);UiSheet.styleInput(input);wrap.addView(input);TextView hint=text("支持订阅清单或单个 JS。插件会请求网络，请使用你信任的来源。",12,muted,false);space(wrap,12);wrap.addView(hint);new UiSheet.Builder(this).setTitle("添加音乐订阅").setView(wrap).setPositiveButton("导入",(d,w)->{tab=3;build();repo.importUrl(input.getText().toString());}).setNegativeButton("取消",null).show();}
    private void configDialog(Source s){LinearLayout form=column();form.setPadding(dp(20),dp(12),dp(20),dp(12));Map<String,EditText> inputs=new LinkedHashMap<>();for(int i=0;i<s.fields.length();i++){JSONObject field=s.fields.optJSONObject(i);if(field==null)continue;String key=field.optString("key");if(key.isEmpty())continue;form.addView(text(field.optString("name",key),14,ink,true));EditText input=new EditText(this);input.setSingleLine(true);input.setText(s.variables.optString(key,field.optString("defaultValue","")));input.setHint(field.optString("hint"));if(field.optString("type").equals("password"))input.setInputType(129);UiSheet.styleInput(input);form.addView(input);space(form,12);inputs.put(key,input);}
        if(inputs.isEmpty())form.addView(text("此插件没有声明可配置项。",14,muted,false));ScrollView view=new ScrollView(this);view.addView(form);new UiSheet.Builder(this).setTitle(s.name+" · 配置").setView(view).setPositiveButton("保存",(d,w)->{try{for(Map.Entry<String,EditText> e:inputs.entrySet())s.variables.put(e.getKey(),e.getValue().getText().toString());s.healthVersion++;s.failures=0;s.playbackHealth.restore();s.message="配置已保存，请复检";repo.save();}catch(Exception e){toast(e.getMessage());}}).setNegativeButton("取消",null).show();}
    private void play(Song song,List<Song> queue,Route route){if(PlaybackService.instance==null){toast("播放器正在准备，请稍后重试");return;}if(route==null)PlaybackUi.play(this,repo,song,visibleResults(queue));else PlaybackService.instance.play(song,visibleResults(queue),route);}
    private void updateRowState(View row){Song song=(Song)row.getTag();PlaybackService p=PlaybackService.instance;boolean active=p!=null&&p.current!=null&&p.current.key.equals(song.key);if(row.isActivated()!=active||row instanceof MainSongRow){row.setActivated(active);if(row instanceof MainSongRow)row.setBackgroundColor(active?0xffe4eee5:Color.TRANSPARENT);}TextView count=row.findViewWithTag("sourceCount");if(count!=null){String value=(repo.playableCount(song)>0?"• ":"")+song.routes.size()+" 源 ›";if(!value.contentEquals(count.getText()))count.setText(value);}}
    private void updateRowStates(){if(scroll!=null)for(View row:scroll.songRows())updateRowState(row);}
    private void updateMiniProgress(){if(miniTitle==null)return;PlaybackService s=PlaybackService.instance;if(s==null||s.current==null)return;long total=s.player.getDuration();miniProgress.setProgress(total>0?(int)(s.displayPosition()*1000/total):0);String lyric=s.currentLyric();String status=s.isRecovering()||s.needsRetry()||lyric.isEmpty()?s.status:lyric;if(!status.contentEquals(miniStatus.getText()))miniStatus.setText(status);}
    private void updateMini(){if(miniTitle==null)return;PlaybackService s=PlaybackService.instance;if(s==null||s.current==null){miniTitle.setText("选择一首歌，开始听");miniStatus.setText("搜索 · 收藏 · 我的歌单");miniButton.setImageResource(R.drawable.player_play);miniButton.setContentDescription("播放");miniProgress.setProgress(0);miniCover.bind(null);return;}miniCover.bind(s.current);long total=s.player.getDuration();miniProgress.setProgress(total>0?(int)(s.displayPosition()*1000/total):0);miniTitle.setText(s.current.title+" · "+s.current.artist);String lyric=s.currentLyric();miniStatus.setText(s.isRecovering()||s.needsRetry()||lyric.isEmpty()?s.status:lyric);miniButton.setImageResource(s.needsRetry()?R.drawable.player_retry:s.wantsPlayback()?R.drawable.player_pause:R.drawable.player_play);miniButton.setContentDescription(s.needsRetry()?"重试播放":s.wantsPlayback()?"暂停":"播放");}
    private void openHelp(){startActivity(new Intent(this,HelpActivity.class));}
    private void openPlayer(){startActivity(new Intent(this,PlayerActivity.class).addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP));}
    private void toast(String message){Toast.makeText(this,message,Toast.LENGTH_LONG).show();}
}
