package app.qingting.music;
import android.app.Activity;import android.graphics.*;import android.graphics.drawable.*;import android.content.res.ColorStateList;import android.os.Bundle;import android.text.*;import android.view.*;import android.widget.*;import java.util.*;import static app.qingting.music.Models.*;
/** Online sheet browsing has no entry point for adding to a local playlist. */
@androidx.media3.common.util.UnstableApi
public final class SheetUi {
 private final Activity a;private final MusicRepository repo;private final Runnable redraw;private final SongListView.Binder songBinder;
 private final int green=0xff245e4f,ink=0xff25332c,muted=0xff7c877f;private String sourceFilter="",filter="";private int resultPosition,resultOffset;
 public SheetUi(Activity a,MusicRepository repo,Runnable redraw,SongListView.Binder songBinder){this.a=a;this.repo=repo;this.redraw=redraw;this.songBinder=songBinder;}
 public void save(Bundle out){out.putString("sheetSourceFilter",sourceFilter);out.putString("sheetSongFilter",filter);out.putInt("sheetResultPosition",resultPosition);out.putInt("sheetResultOffset",resultOffset);}
 public void restore(Bundle in){if(in==null)return;sourceFilter=in.getString("sheetSourceFilter","");filter=in.getString("sheetSongFilter","");resultPosition=in.getInt("sheetResultPosition");resultOffset=in.getInt("sheetResultOffset");}
 public void newSearch(){sourceFilter="";filter="";resultPosition=resultOffset=0;}
 private Sheets.Detail filteredDetail;private String lastFilter="";private List<Song> displayed=Collections.emptyList();
 public List<Song> visibleSongs(){if(filteredDetail!=repo.sheets.detail||!lastFilter.equals(filter)){filteredDetail=repo.sheets.detail;lastFilter=filter;displayed=filteredDetail==null?Collections.emptyList():LibraryState.filtered(filteredDetail.songs,filter,0);}return displayed;}
 public String signature(){OnlineSheets s=repo.sheets;return s.detail==null?"results:"+s.revision+":"+sourceFilter:"detail:"+System.identityHashCode(s.detail)+":"+s.loadingDetail+":"+s.detailError;}
 public boolean back(SongListView list){if(repo.sheets.detail==null)return false;repo.cancelVisibleChecks();repo.sheets.closeDetail();filter="";redraw.run();list.post(()->list.setSelectionFromTop(resultPosition,resultOffset));return true;}
 private int dp(int value){return Math.round(value*a.getResources().getDisplayMetrics().density);}
 private LinearLayout row(){LinearLayout v=new LinearLayout(a);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
 private LinearLayout column(){LinearLayout v=row();v.setOrientation(LinearLayout.VERTICAL);v.setGravity(Gravity.START);return v;}
 private void weight(LinearLayout parent,View child){parent.addView(child,new LinearLayout.LayoutParams(0,-2,1));}
 private void space(LinearLayout parent,int n){parent.addView(new View(a),new LinearLayout.LayoutParams(1,dp(n)));}
 private TextView text(String value,int size,int color){TextView t=new TextView(a);t.setText(value);t.setTextSize(size);t.setTextColor(color);return t;}
 private GradientDrawable shape(int color){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(12));return d;}
 private TextView action(String label,Runnable run){TextView v=text(label,14,green);v.setGravity(Gravity.CENTER);v.setMinHeight(dp(48));v.setPadding(dp(12),0,dp(12),0);v.setBackground(new RippleDrawable(ColorStateList.valueOf(0x18245e4f),shape(0xffe9eee7),null));v.setOnClickListener(w->run.run());return v;}
 private void single(TextView t){t.setSingleLine(true);t.setEllipsize(TextUtils.TruncateAt.END);}
 public void render(SongListView list){if(repo.sheets.detail!=null){detail(list);return;}OnlineSheets s=repo.sheets;LinearLayout host=list.header;
  LinearLayout top=row();TextView heading=text("歌单搜索",22,ink);heading.setTypeface(null,Typeface.BOLD);weight(top,heading);top.addView(text(s.items.size()+" 个"+(s.searching?" · 搜索中":""),12,muted));host.addView(top);space(host,12);
  LinearLayout tools=row();String selected="全部来源";for(Sheets.Item item:s.items)if(item.sourceId.equals(sourceFilter)){selected=item.sourceName;break;}weight(tools,action(selected+" · "+s.supported.size()+" 个支持源",()->chooseSource(list)));tools.addView(action("状态",this::sourceStatus));tools.addView(action("刷新",()->{newSearch();s.search(s.query,true);}));host.addView(tools);space(host,12);
  List<Sheets.Item> visible=new ArrayList<>();for(Sheets.Item item:s.items)if(sourceFilter.isEmpty()||sourceFilter.equals(item.sourceId))visible.add(item);
  list.items(visible,2,(value,old,parent)->{Sheets.Item item=(Sheets.Item)value;SheetRow row=old instanceof SheetRow?(SheetRow)old:new SheetRow();row.bind(item,list);return row;});
  if(visible.isEmpty()){space(host,24);host.addView(text(s.searching?"正在查找歌单…":"没有找到歌单",17,ink));space(host,8);host.addView(text(s.searching?"结果会陆续显示，无需等待所有来源。":sourceFilter.isEmpty()?"换个关键词，或查看来源状态后重试。":"试试切换到全部来源。",13,muted));}
  if(s.hasMore()&&!s.searching)list.footer.addView(action("加载更多 / 重试失败来源",s::loadMore));
 }
 private final class SheetRow extends LinearLayout{
  final ArtworkView cover;final TextView title,subtitle;Sheets.Item item;SongListView list;
  SheetRow(){super(a);setOrientation(HORIZONTAL);setGravity(Gravity.CENTER_VERTICAL);setPadding(0,dp(8),0,dp(8));setMinimumHeight(dp(80));cover=new ArtworkView(a,false);cover.setImportantForAccessibility(View.IMPORTANT_FOR_ACCESSIBILITY_NO);addView(cover,new LinearLayout.LayoutParams(dp(56),dp(56)));LinearLayout copy=column();copy.setPadding(dp(12),0,dp(8),0);title=text("",16,ink);single(title);copy.addView(title);space(copy,6);subtitle=text("",12,muted);single(subtitle);copy.addView(subtitle);weight(this,copy);ImageView arrow=new ImageView(a);arrow.setImageResource(R.drawable.library_back);arrow.setRotation(180);arrow.setImageTintList(ColorStateList.valueOf(muted));addView(arrow,new LinearLayout.LayoutParams(dp(18),dp(18)));setBackground(new RippleDrawable(ColorStateList.valueOf(0x18245e4f),null,shape(Color.WHITE)));setOnClickListener(v->{resultPosition=list.getFirstVisiblePosition();resultOffset=list.getChildCount()==0?0:list.getChildAt(0).getTop();filter="";repo.cancelVisibleChecks();repo.sheets.open(item,false);redraw.run();});}
  void bind(Sheets.Item item,SongListView list){this.item=item;this.list=list;cover.bindUrl(item.artwork());title.setText(item.title());subtitle.setText(item.subtitle());setContentDescription("打开歌单 "+item.title()+"，"+item.subtitle());}
 }
 private void chooseSource(SongListView list){LinkedHashMap<String,String> options=new LinkedHashMap<>();options.put("","全部来源");for(String id:repo.sheets.supported){Source s=repo.source(id);if(s!=null)options.put(id,s.name);}List<String> keys=new ArrayList<>(options.keySet());new UiSheet.Builder(a).setTitle("歌单来源").setSingleChoiceItems(options.values().toArray(new String[0]),keys.indexOf(sourceFilter),(d,w)->{sourceFilter=keys.get(w);d.dismiss();redraw.run();list.setSelection(0);}).show();}
 private void sourceStatus(){StringBuilder message=new StringBuilder();for(Map.Entry<String,String> entry:repo.sheets.states.entrySet()){Source source=repo.source(entry.getKey());if(source!=null)message.append(source.name).append(" · ").append(entry.getValue()).append("\n\n");}new UiSheet.Builder(a).setTitle("歌单来源状态").setMessage(message.length()==0?"暂无来源，请先导入订阅。":message.toString()).setPositiveButton("关闭",null).show();}
 private SongListView boundList;private String boundKey="";private EditText detailInput;private TextView detailTitle,detailSubtitle,detailIntro,detailPlay,detailStatus,detailRefresh;private ArtworkView detailCover;
 private void detail(SongListView list){OnlineSheets s=repo.sheets;Sheets.Detail detail=s.detail;LinearLayout host=list.header;boundList=list;boundKey=detail.item.config+detail.item.key;
  LinearLayout nav=row();TextView back=action("返回歌单搜索",()->back(list));back.setGravity(Gravity.CENTER_VERTICAL);back.setPadding(0,0,dp(12),0);back.setBackgroundColor(Color.TRANSPARENT);Drawable arrow=a.getDrawable(R.drawable.library_back);arrow.setBounds(0,0,dp(20),dp(20));back.setCompoundDrawablesRelative(arrow,null,null,null);back.setCompoundDrawablePadding(dp(8));weight(nav,back);detailRefresh=action("刷新",()->{if(s.detail!=null)s.open(s.detail.item,true);});nav.addView(detailRefresh);host.addView(nav);space(host,12);
  LinearLayout heading=row();detailCover=new ArtworkView(a,false);heading.addView(detailCover,new LinearLayout.LayoutParams(dp(64),dp(64)));LinearLayout copy=column();copy.setPadding(dp(12),0,0,0);detailTitle=text("",21,ink);detailTitle.setTypeface(null,Typeface.BOLD);detailTitle.setMaxLines(2);detailTitle.setEllipsize(TextUtils.TruncateAt.END);copy.addView(detailTitle);space(copy,5);detailSubtitle=text("",12,muted);copy.addView(detailSubtitle);weight(heading,copy);host.addView(heading);space(host,10);
  detailIntro=text("",13,muted);detailIntro.setMaxLines(2);detailIntro.setEllipsize(TextUtils.TruncateAt.END);detailIntro.setOnClickListener(v->{if(s.detail!=null)new UiSheet.Builder(a).setTitle(s.detail.item.title()).setMessage(SongText.clean(s.detail.raw.optString("description"))).setPositiveButton("关闭",null).show();});host.addView(detailIntro);space(host,14);
  detailInput=new EditText(a);detailInput.setSingleLine(true);detailInput.setTextSize(14);detailInput.setHint("在已加载歌曲中搜索");UiSheet.styleInput(detailInput);detailInput.setText(filter);host.addView(detailInput,new LinearLayout.LayoutParams(-1,dp(48)));space(host,8);
  detailPlay=action("",()->{List<Song> songs=visibleSongs();if(!songs.isEmpty())PlaybackUi.play(a,repo,songs.get(0),songs);});host.addView(detailPlay);space(host,8);detailStatus=text("",12,muted);host.addView(detailStatus);updateDetail(list);
  detailInput.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence v,int st,int c,int after){}public void afterTextChanged(Editable e){}public void onTextChanged(CharSequence v,int st,int before,int count){filter=v.toString();updateDetail(list);}});
 }
 /** Keep the live EditText (including IME composing spans) while pages arrive. */
 public boolean updateDetail(SongListView list){OnlineSheets s=repo.sheets;Sheets.Detail detail=s.detail;if(detail==null||boundList!=list||detailInput==null||detailInput.getParent()!=list.header||!boundKey.equals(detail.item.config+detail.item.key))return false;
  detailRefresh.setEnabled(!s.loadingDetail);detailTitle.setText(SongText.clean(detail.raw.optString("title",detail.item.title())));detailSubtitle.setText(detail.item.subtitle());String cover=detail.raw.optString("artwork",detail.item.artwork());detailCover.bindUrl(cover);String description=SongText.clean(detail.raw.optString("description"));detailIntro.setText(description);detailIntro.setVisibility(description.isEmpty()?View.GONE:View.VISIBLE);
  List<Song> visible=visibleSongs();list.songs(visible,0,songBinder);detailPlay.setEnabled(!visible.isEmpty());detailPlay.setAlpha(visible.isEmpty()?.4f:1f);detailPlay.setText((filter.isEmpty()?"播放已加载歌曲":"播放筛选结果")+" · "+visible.size()+" 首");detailStatus.setText(s.loadingDetail?"正在加载…":!s.detailError.isEmpty()?"加载失败："+s.detailError:detail.songs.isEmpty()?(detail.end?"这张歌单暂无歌曲":"当前页暂无歌曲，请继续加载"):visible.isEmpty()?"没有匹配歌曲":detail.end?"已全部加载":"已加载 "+detail.songs.size()+" 首，可继续加载");
  list.footer.removeAllViews();if(!s.loadingDetail&&(!detail.end||!s.detailError.isEmpty()))list.footer.addView(action(s.detailError.isEmpty()?"加载更多歌曲":"重试加载",()->{if(!s.detailError.isEmpty())s.retryDetail();else s.loadDetail();}));return true;
 }
}
