package app.qingting.music;

import android.app.*;import android.content.*;import android.content.res.ColorStateList;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.*;import android.os.Bundle;import android.text.*;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import java.util.*;
/** Shared bottom actions and forms. Playback and library ownership stay with their callers. */
public final class UiSheet extends Dialog {
 private final Builder spec;private final Map<Integer,Button> buttons=new HashMap<>();
 private final Application.ActivityLifecycleCallbacks lifecycle=new Application.ActivityLifecycleCallbacks(){public void onActivityCreated(Activity a,Bundle b){}public void onActivityStarted(Activity a){}public void onActivityResumed(Activity a){}public void onActivityPaused(Activity a){}public void onActivityStopped(Activity a){}public void onActivitySaveInstanceState(Activity a,Bundle b){}public void onActivityDestroyed(Activity a){if(a==spec.activity)dismiss();}};
 private UiSheet(Builder spec){super(spec.activity);this.spec=spec;setOwnerActivity(spec.activity);}
 static int dp(Context c,int n){return (int)(n*c.getResources().getDisplayMetrics().density+.5f);}
 static GradientDrawable shape(Context c,int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(c,radius));return d;}
 private TextView text(String value,int size,int color,boolean bold){TextView t=new TextView(getContext());t.setText(value);t.setTextSize(size);t.setTextColor(color);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
 private LinearLayout column(){LinearLayout v=new LinearLayout(getContext());v.setOrientation(LinearLayout.VERTICAL);return v;}
 private boolean destructive(String label){return label.contains("删除")||label.contains("移出")||label.contains("清空")||label.contains("取消收藏");}
 private int icon(String label){if(destructive(label))return R.drawable.ui_remove;if(label.contains("收藏"))return R.drawable.player_heart;if(label.contains("时间")||label.contains("分钟")||label.contains("定时"))return R.drawable.library_recent;if(label.contains("来源")||label.contains("线路"))return R.drawable.ui_sources;if(label.contains("新建")||label.contains("添加"))return R.drawable.library_add;if(label.contains("播放"))return R.drawable.player_play;return R.drawable.library_playlist;}
 @Override protected void onCreate(Bundle state){super.onCreate(state);requestWindowFeature(Window.FEATURE_NO_TITLE);setCanceledOnTouchOutside(true);Context c=getContext();LinearLayout root=column();root.setPadding(dp(c,20),dp(c,10),dp(c,20),dp(c,12));root.setBackground(shape(c,0xfffcfdfb,24));
  FrameLayout grab=new FrameLayout(c);View handle=new View(c);handle.setBackground(shape(c,0xffd5ded5,2));grab.addView(handle,new FrameLayout.LayoutParams(dp(c,32),dp(c,4),Gravity.CENTER));root.addView(grab,new LinearLayout.LayoutParams(-1,dp(c,24)));grab.setContentDescription("下拉关闭面板");float[] down={0};grab.setOnTouchListener((v,event)->{if(event.getActionMasked()==MotionEvent.ACTION_DOWN){down[0]=event.getRawY();return true;}if(event.getActionMasked()==MotionEvent.ACTION_MOVE){root.setTranslationY(Math.max(0,event.getRawY()-down[0]));return true;}if(event.getActionMasked()==MotionEvent.ACTION_UP||event.getActionMasked()==MotionEvent.ACTION_CANCEL){if(event.getActionMasked()==MotionEvent.ACTION_UP&&root.getTranslationY()>dp(c,64))dismiss();else root.animate().translationY(0).setDuration(150).start();v.performClick();return true;}return false;});
  LinearLayout header=new LinearLayout(c);header.setGravity(Gravity.CENTER_VERTICAL);TextView title=text(spec.title,20,0xff25332c,true);title.setMaxLines(2);title.setEllipsize(TextUtils.TruncateAt.END);header.addView(title,new LinearLayout.LayoutParams(0,-2,1));Button close=action("关闭",false,()->dismiss());close.setContentDescription("关闭面板");header.addView(close,new LinearLayout.LayoutParams(dp(c,64),dp(c,48)));root.addView(header);
  ScrollView scroll=new ScrollView(c){@Override protected void onMeasure(int w,int h){int cap=(int)(getResources().getDisplayMetrics().heightPixels*.52f);super.onMeasure(w,MeasureSpec.makeMeasureSpec(Math.min(MeasureSpec.getMode(h)==MeasureSpec.UNSPECIFIED?cap:MeasureSpec.getSize(h),cap),MeasureSpec.AT_MOST));}};scroll.setFillViewport(false);LinearLayout body=column();body.setPadding(0,dp(c,8),0,dp(c,8));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,-2));
  if(!spec.message.isEmpty()){TextView message=text(spec.message,14,0xff758078,false);message.setLineSpacing(dp(c,5),1);message.setTextIsSelectable(true);message.setPadding(0,0,0,dp(c,14));body.addView(message);}
  if(spec.view!=null){if(spec.view instanceof EditText)styleInput((EditText)spec.view);body.addView(spec.view,new LinearLayout.LayoutParams(-1,-2));}
  List<Integer> order=new ArrayList<>();if(spec.items!=null)for(int pass=0;pass<2;pass++)for(int i=0;i<spec.items.length;i++)if((!spec.choices&&destructive(spec.items[i]))==(pass==1))order.add(i);boolean separated=false;for(int i:order){final int index=i;String label=spec.items[i];boolean danger=!spec.choices&&destructive(label);if(danger&&!separated){View rule=new View(c);rule.setBackgroundColor(0xffe4e9e1);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(c,1));rp.topMargin=rp.bottomMargin=dp(c,8);body.addView(rule,rp);separated=true;}
   LinearLayout item=new LinearLayout(c);item.setGravity(Gravity.CENTER_VERTICAL);item.setMinimumHeight(dp(c,56));item.setPadding(dp(c,8),dp(c,8),dp(c,8),dp(c,8));item.setBackground(new RippleDrawable(ColorStateList.valueOf(0x18245e4f),shape(c,index==spec.checked?0xffe9f0e7:Color.TRANSPARENT,12),null));ImageView image=new ImageView(c);image.setImageResource(spec.choices?(label.startsWith("＋")?R.drawable.library_add:spec.title.contains("源")||spec.title.contains("线路")?R.drawable.ui_sources:R.drawable.library_playlist):icon(label));image.setImageTintList(ColorStateList.valueOf(danger?0xffb94e47:0xff245e4f));item.addView(image,new LinearLayout.LayoutParams(dp(c,22),dp(c,22)));TextView name=text(label,15,danger?0xffb94e47:0xff25332c,false);name.setPadding(dp(c,14),0,dp(c,8),0);item.addView(name,new LinearLayout.LayoutParams(0,-2,1));if(index==spec.checked){TextView check=text("✓",18,0xff245e4f,true);item.addView(check);}item.setContentDescription(label+(index==spec.checked?"，已选":""));item.setOnClickListener(v->{dismiss();if(spec.itemClick!=null)spec.itemClick.onClick(this,index);});body.addView(item);
  }
  for(int which:new int[]{DialogInterface.BUTTON_POSITIVE,DialogInterface.BUTTON_NEUTRAL,DialogInterface.BUTTON_NEGATIVE}){String label=spec.labels.get(which);if(label==null)continue;Button button=action(label,which==DialogInterface.BUTTON_POSITIVE,()->{DialogInterface.OnClickListener listener=spec.actions.get(which);if(listener!=null)listener.onClick(this,which);dismiss();});buttons.put(which,button);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(c,48));bp.topMargin=dp(c,6);body.addView(button,bp);}
  setContentView(root);Window window=getWindow();if(window!=null){window.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));window.setGravity(Gravity.BOTTOM);window.setDimAmount(.32f);window.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);window.setNavigationBarColor(0xfffcfdfb);}
 }
 private Button action(String label,boolean primary,Runnable run){Button button=new Button(getContext());button.setText(label);button.setTextSize(14);button.setAllCaps(false);button.setTextColor(primary?Color.WHITE:0xff245e4f);button.setBackground(new RippleDrawable(ColorStateList.valueOf(0x22245e4f),shape(getContext(),primary?(destructive(label)?0xffb94e47:0xff245e4f):Color.TRANSPARENT,14),null));button.setOnClickListener(v->run.run());return button;}
 @Override protected void onStart(){super.onStart();spec.activity.getApplication().registerActivityLifecycleCallbacks(lifecycle);if(getWindow()!=null)getWindow().setLayout(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);}
 @Override protected void onStop(){spec.activity.getApplication().unregisterActivityLifecycleCallbacks(lifecycle);super.onStop();}
 public Button getButton(int which){return buttons.get(which);}
 public static void styleInput(EditText input){Context c=input.getContext();input.setTextSize(16);input.setTextColor(0xff25332c);input.setHintTextColor(0xff879087);input.setBackground(shape(c,0xffedf1e9,14));input.setPadding(dp(c,16),dp(c,14),dp(c,16),dp(c,14));input.setMinimumHeight(dp(c,52));}
 public static final class Builder {
  final Activity activity;String title="",message="";View view;String[] items;boolean choices;int checked=-1;DialogInterface.OnClickListener itemClick;final Map<Integer,String> labels=new HashMap<>();final Map<Integer,DialogInterface.OnClickListener> actions=new HashMap<>();
  public Builder(Activity activity){this.activity=activity;}
  public Builder setTitle(String value){title=value;return this;}public Builder setMessage(String value){message=value;return this;}public Builder setView(View value){view=value;return this;}
  public Builder setItems(String[] values,DialogInterface.OnClickListener click){items=values;itemClick=click;return this;}public Builder setSingleChoiceItems(String[] values,int selected,DialogInterface.OnClickListener click){choices=true;checked=selected;return setItems(values,click);}
  private Builder button(int which,String label,DialogInterface.OnClickListener click){labels.put(which,label);actions.put(which,click);return this;}
  public Builder setPositiveButton(String label,DialogInterface.OnClickListener click){return button(-1,label,click);}public Builder setNegativeButton(String label,DialogInterface.OnClickListener click){return button(-2,label,click);}public Builder setNeutralButton(String label,DialogInterface.OnClickListener click){return button(-3,label,click);}
  public UiSheet create(){return new UiSheet(this);}public UiSheet show(){UiSheet dialog=create();dialog.show();return dialog;}
 }
}
